# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/midi-rae',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/midi-rae',
                'lib_path': 'midi_rae'},
  'syms': {'midi_rae.core': {'midi_rae.core.foo': ('core.html#foo', 'midi_rae/core.py')}}}
