"""data handling routines"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto #0
__all__ = ['SCHEME_NAMES', 'TARGET_NAMES', 'shift_no_wrap', 'sample_shift', 'note_length_weights', 'AnchorDataset',
           'sample_shifts', 'PRPairDataset', 'ShiftedTripletDataset', 'PreEncodedChunkDataset']

# %% ../nbs/01_data.ipynb #b96051a7
import os 
import torch
from torch.utils.data import Dataset, Sampler
from glob import glob 
import random
from PIL import Image
import numpy as np
from scipy.stats import truncnorm
from scipy.ndimage import label

from .utils import *
from .core import *

# %% ../nbs/01_data.ipynb #56d556e3-fb85-4669-934c-33f0d93fb142
def shift_no_wrap(x, shifts, dims):
    """Drop-in replacement for torch.roll with zero-fill instead of wrap."""
    if shifts == 0: return x
    out = torch.roll(x, shifts=shifts, dims=dims)
    n = abs(shifts)
    if shifts > 0: out.narrow(dims, 0, n).zero_()
    else: out.narrow(dims, out.size(dims)-n, n).zero_()
    return out

# %% ../nbs/01_data.ipynb #9cbee8f8-d8ff-4f74-882e-7dde4db4f684
def sample_shift(max_shift, sigma=7, size=None):
    "Samples shifts amounts as integers from a truncated normal distribution"
    a, b = -max_shift / sigma, max_shift / sigma
    samples = truncnorm.rvs(a, b, loc=0, scale=sigma, size=size)
    if size is None: return int(round(samples))
    return np.rint(samples).astype(int)

# %% ../nbs/01_data.ipynb #7250ec68-df48-486b-8b30-00b9df5cf2cf
def note_length_weights(img, min_weight=1.0, power=0.5):
  "note weight is inversely proportional to note length"
  weights = np.ones_like(img, dtype=np.float32)
  lengths = []
  for row in range(img.shape[0]):  # horizontal slices
      labeled, n = label(img[row] > 0)
      for i in range(1, n+1):
          run = (labeled == i)
          length = run.sum()
          lengths.append(length)
          weights[row, run] = (1.0 / length) ** power
  #return weights / weights.mean()  # normalize so mean weight = 1
  if lengths != []: 
      median_length = np.median(lengths)
      weights = weights * (median_length)**power  # normalize by median length
  return weights 

# %% ../nbs/01_data.ipynb #ea0fb421-49e9-4082-8081-e30300c5a213
class AnchorDataset(Dataset):
    "piano roll pair dataset"
    def __init__(self, 
            image_dataset_dir='~/datasets/POP909_images_basic/', 
            crop_size=(128,128),  # int for square of tuple for rectangle 
            split='train',
            val_fraction=0.1,
            seed=42,
            verbose=True,
            aug_y_max=12, # number of pitch semitones +/- for data augmentation
            sigma=7, # truncnorm tightness param for aug_y
            pad_x=(0,0), # (left, right) : crop wider to (crop_sizw-pad_x[0], crop_size+pad_x[1])
            ):
        self.crop_size, self.aug_y_max, self.sigma, self.pad_x = crop_size, aug_y_max, sigma, pad_x
        
        # Load and split filenames
        all_filenames = glob(os.path.join(os.path.expandvars(os.path.expanduser(image_dataset_dir)), '**/*.png'), recursive=True)
        rng = random.Random(seed)
        shuffled = all_filenames.copy()
        rng.shuffle(shuffled)
        split_idx = int(len(shuffled) * (1 - val_fraction))
        self.filenames = shuffled[:split_idx] if split == 'train' else shuffled[split_idx:]            
        self.actual_len = len(self.filenames)

# %% ../nbs/01_data.ipynb #9b1f47bb-c1cc-4a0a-a5f3-5083b91eca58
def sample_shifts(max_x, max_y, sigma):
    "Get X and Y shifts; one of them must be non-zero"
    while True:
        sx, sy = sample_shift(max_x, sigma), sample_shift(max_y, sigma)
        if sx != 0 or sy != 0: return sx, sy

# %% ../nbs/01_data.ipynb #a164c279
class PRPairDataset(Dataset):
    "piano roll pair dataset"
    def __init__(self, 
            image_dataset_dir='~/datasets/POP909_images_basic', 
            crop_size=128, 
            max_shift_x=12, 
            max_shift_y=12,
            split='train',
            val_fraction=0.1,
            seed=42,
            verbose=True,
            sigma=7,               # param for truncnorm dist for sampling shifts/deltas
            shared=None,   # Possible shared memory thing for changing deets on the fly
            ):
        self.crop_size, self.max_shift_x, self.max_shift_y = crop_size, max_shift_x, max_shift_y
        self.sigma, self.shared = sigma, shared
        
        # Load and split filenames
        all_filenames = glob(os.path.join(os.path.expandvars(os.path.expanduser(image_dataset_dir)), '**/*.png'), recursive=True)
        rng = random.Random(seed)
        shuffled = all_filenames.copy()
        rng.shuffle(shuffled)
        split_idx = int(len(shuffled) * (1 - val_fraction))
        
        if split == 'train':
            self.filenames = shuffled[:split_idx]
        else:
            self.filenames = shuffled[split_idx:]

# %% ../nbs/01_data.ipynb #13ba9ffc-51c2-4b85-b357-4e1ea53e0a23
SCHEME_NAMES = {  0: 'pitch-pitch',    1: 'time-time',        2: 'pitch-time'}
TARGET_NAMES = {1.0: 'parallel',    -1.0: 'anti-parallel',  0.0: 'orthogonal'}

class ShiftedTripletDataset(AnchorDataset):
    """Piano roll triplet dataset inheriting from AnchorDataset."""
    def __init__(self, 
            max_shift_x=12, 
            max_shift_y=12,
            shared=None,
            aug_y_max=6, 
            **kwargs,   # passes through to AnchorDataset.__init__
            ):
        super().__init__(aug_y_max=aug_y_max, **kwargs)
        self.max_shift_x, self.max_shift_y = max_shift_x, max_shift_y
        self.shared = shared

    def __getitem__(self, idx, requested_scheme=None, requested_target=None):
        # --- sample shifts sx1, sy1, sx2, sy2 from distribution
        msx = self.shared['training']['max_shift_x'] if self.shared else self.max_shift_x
        msy = self.shared['training']['max_shift_y'] if self.shared else self.max_shift_y
        while True:
            scheme = torch.randint(0, 3, (1,)).item() if requested_scheme is None else int(requested_scheme)
            if requested_target is not None and requested_target != 0: scheme = torch.randint(0, 2, (1,)).item()
            sign1 = 1 if torch.rand(1) > 0.5 else -1
            if requested_target is None: 
                sign2 = 1 if torch.rand(1) > 0.5 else -1
            else: 
                sign2 = sign1 * int(requested_target)
            if scheme == 0:    
                s1 = abs(sample_shift(msy, self.sigma)) or 1  # 0's are handled explicitly below according to scheme
                s2 = abs(sample_shift(msy, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = sign1*s1, 0, sign2*s2, 0    # both shift in y
            elif scheme == 1:  
                s1 = abs(sample_shift(msx, self.sigma)) or 1
                s2 = abs(sample_shift(msx, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = 0, sign1*s1, 0, sign2*s2    # both shifts in x
            else:                                                
                s1 = abs(sample_shift(msy, self.sigma)) or 1
                s2 = abs(sample_shift(msx, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = sign1*s1, 0, 0, sign2*s2 # first one y, second one x
            if not ((dy1==dy2) and (dx1==dx2)) and not (dx1==0 and dy1==0) and not (dx2==0 and dy2==0): break 
        target = float(np.sign(sign1 * sign2)) if scheme < 2 else 0.0   
        if requested_target is not None and torch.abs(target-requested_target) > 1e-3: 
            raise UserWarning(f"Warning: requested_target = {requested_target}, but got target = {target}")
        # --- Now we know what shifts we want to do, next let's construct the crops.

        # obtain the wider anchor, with sufficient padding later crops
        pad_x = ( abs(min(min(dx1,dx2), 0)), max(max(dx1, dx2), 0) ) 
        anchor = super().__getitem__(idx, pad_x=pad_x)
        img = anchor['img']  # (1, H, crop_size + 2*sx)  <-- note the extra "1," for what follows!
        cs = self.crop_size if isinstance(self.crop_size, int) else self.crop_size[1]  # width dimension

        # crops in x
        c1 = img[:,:, pad_x[0]+dx1: pad_x[0]+dx1+cs]
        c2 = img[:,:, pad_x[0]+dx2: pad_x[0]+dx2+cs]
        img = img[:,:,pad_x[0]:     pad_x[0]+cs]       # crop anchor to final size

        # shift c1 and c2 images in y 
        c1 = shift_no_wrap(c1, shifts=dy1, dims=1) 
        c2 = shift_no_wrap(c2, shifts=dy2, dims=1)
        return {
            'img1': img, 'img2': c1, 'img3': c2,
            'deltas': torch.tensor([[dy1,dx1],[dy2,dx2]], dtype=torch.int),
            'file_idx': anchor['file_idx'], 'scheme': scheme, 'target': torch.tensor(target),
        }

# %% ../nbs/01_data.ipynb #510bad1c
class PreEncodedChunkDataset(Dataset):
    """Lazy-loading dataset for preencode chunk files (list-of-batch-dicts format).
    Each chunk is a list of dicts with emb keys (list of level tensors, each (B,N,D))
    and optionally img keys ((B,C,H,W) bool). Flattens to individual samples.

    Args:
        encoded_dir: directory containing {split}_chunk*.pt files
        split:       'train' or 'val'
        emb_key:     which embedding to return ('emb1', 'emb2', 'emb3')
        img_key:     which image to return ('img1', etc.), or None to omit images

    Returns (emb_levels, img) tuples, or just emb_levels when img_key=None."""
    def __init__(self, encoded_dir, split='train', emb_key='emb1', img_key='img1'):
        self.emb_key, self.img_key = emb_key, img_key
        encoded_dir = os.path.expandvars(os.path.expanduser(str(encoded_dir)))
        self.files = sorted(glob(os.path.join(encoded_dir, f'{split}_chunk*.pt')))
        assert self.files, f"No {split}_chunk*.pt files in {encoded_dir}"
        self.index = []
        self.chunk_sample_ranges = {}
