"""data handling routines"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto #0
__all__ = ['SCHEME_NAMES', 'TARGET_NAMES', 'shift_no_wrap', 'sample_shift', 'note_length_weights', 'AnchorDataset',
           'sample_shifts', 'PRPairDataset', 'ShiftedTripletDataset', 'PreEncodedChunkDataset', 'ChunkShuffleSampler',
           'collate_emb_levels', 'collate_preencode', 'get_pos_cache', 'emb_levels_to_enc_out', 'EmbeddingDataset',
           'ConditionalFlowDataset', 'ConditionalFlowChunkSampler']

# %% ../nbs/01_data.ipynb #b96051a7
import os 
import torch
from torch.utils.data import Dataset, Sampler
from glob import glob 
from pathlib import Path
import random
from PIL import Image
import numpy as np
from scipy.stats import truncnorm
from scipy.ndimage import label

from .utils import *
from .core import *

# %% ../nbs/01_data.ipynb #56d556e3-fb85-4669-934c-33f0d93fb142
def shift_no_wrap(x, shifts, dims):
    """Drop-in replacement for torch.roll with zero-fill instead of wrap."""
    if shifts == 0: return x
    out = torch.roll(x, shifts=shifts, dims=dims)
    n = abs(shifts)
    if shifts > 0: out.narrow(dims, 0, n).zero_()
    else: out.narrow(dims, out.size(dims)-n, n).zero_()
    return out

# %% ../nbs/01_data.ipynb #9cbee8f8-d8ff-4f74-882e-7dde4db4f684
def sample_shift(max_shift, sigma=7, size=None):
    "Samples shifts amounts as integers from a truncated normal distribution"
    a, b = -max_shift / sigma, max_shift / sigma
    samples = truncnorm.rvs(a, b, loc=0, scale=sigma, size=size)
    if size is None: return int(round(samples))
    return np.rint(samples).astype(int)

# %% ../nbs/01_data.ipynb #7250ec68-df48-486b-8b30-00b9df5cf2cf
def note_length_weights(img, min_weight=1.0, power=0.5):
  "note weight is inversely proportional to note length"
  from scipy.ndimage import label

  weights = np.ones_like(img, dtype=np.float32)
  lengths = []
  for row in range(img.shape[0]):  # horizontal slices
      labeled, n = label(img[row] > 0)
      for i in range(1, n+1):
          run = (labeled == i)
          length = run.sum()
          lengths.append(length)
          weights[row, run] = (1.0 / length) ** power
  #return weights / weights.mean()  # normalize so mean weight = 1
  if lengths != []: 
      median_length = np.median(lengths)
      weights = weights * (median_length)**power  # normalize by median length
  return weights 

# %% ../nbs/01_data.ipynb #ea0fb421-49e9-4082-8081-e30300c5a213
class AnchorDataset(Dataset):
    "piano roll pair dataset"
    def __init__(self, 
            image_dataset_dir='$HOME/datasets/POP909_images_basic/', 
            crop_size=(128,128),  # int for square of tuple for rectangle 
            split='train',
            val_fraction=0.1,
            seed=42,
            verbose=True,
            aug_y_max=12, # number of pitch semitones +/- for data augmentation
            sigma=7, # truncnorm tightness param for aug_y
            pad_x=(0,0), # (left, right) : crop wider to (crop_sizw-pad_x[0], crop_size+pad_x[1])
            ):
        self.crop_size, self.aug_y_max, self.sigma, self.pad_x = crop_size, aug_y_max, sigma, pad_x
        
        # Load and split filenames
        all_filenames = glob(os.path.join(os.path.expandvars(os.path.expanduser(image_dataset_dir)), '**/*.png'), recursive=True)
        rng = random.Random(seed)
        shuffled = all_filenames.copy()
        rng.shuffle(shuffled)
        split_idx = int(len(shuffled) * (1 - val_fraction))
        self.filenames = shuffled[:split_idx] if split == 'train' else shuffled[split_idx:]            
        self.actual_len = len(self.filenames)
        self.images, self.note_weights = [], []
        if verbose: print(f"Loading {self.actual_len} {split} files from {image_dataset_dir}... ",end="\n")
        for f in self.filenames: 
            img = Image.open(f).convert('L')  # grayscale
            img =  (np.array(img, dtype=np.uint8) > 0).astype(np.uint8) # binary uint8
            self.images.append(img)
            self.note_weights.append(note_length_weights(img).astype(np.float16)) # float16 saves system RAM, autocasts to bfloat16 later
        if verbose: print(f"Finished loading.")

    def __len__(self):
        return self.actual_len * 100  # arbitrary large number for epoch length

    def __getitem__(self, idx, pad_x=None, crop_size=None):
        if crop_size is None: crop_size = self.crop_size
        if isinstance(crop_size, int): crop_size = (crop_size, crop_size)
        if pad_x is None: pad_x = self.pad_x 

        # ignore idx, just randomly sample
        file_idx = random.randint(0, self.actual_len - 1)
        img = torch.from_numpy( self.images[file_idx] ).float()
        note_weights = torch.from_numpy(self.note_weights[file_idx])

        # augmentation in y: transpose entire img in y (pitch)
        aug_y = sample_shift( self.aug_y_max, self.sigma) 
        img = shift_no_wrap(img, shifts=aug_y, dims=0) # prevent low/high notes from wrapping
        note_weights = shift_no_wrap(note_weights, shifts=aug_y, dims=0) 
        
        # cropping in x 
        h, w = img.shape
        min_loc, max_loc = 0+pad_x[0], w - crop_size[1] - pad_x[1]
        loc = random.randint(min_loc, max_loc)      
        img = img[:, loc-pad_x[0]: loc + crop_size[1]+pad_x[1]]  # crop horizontally
        note_weights = note_weights[:, loc-pad_x[0]: loc + crop_size[1]+pad_x[1]]  # crop horizontally

        # optional: additional cropping in y: 
        if crop_size[0] < img.shape[0]: 
            mid, hc = img.shape[0]//2,  crop_size[0]//2
            img = img[mid-hc: mid+hc, :]
            note_weights = note_weights[mid-hc: mid+hc, :]

        return {
            'img': img.unsqueeze(0),  # add channel dim: (1, 128+pad_x[0], 128+pad_x[1])
            'file_idx': file_idx,
            'note_weights': note_weights.unsqueeze(0),
        }

# %% ../nbs/01_data.ipynb #9b1f47bb-c1cc-4a0a-a5f3-5083b91eca58
def sample_shifts(max_x, max_y, sigma):
    "Get X and Y shifts; one of them must be non-zero"
    while True:
        sx, sy = sample_shift(max_x, sigma), sample_shift(max_y, sigma)
        if sx != 0 or sy != 0: return sx, sy

# %% ../nbs/01_data.ipynb #a164c279
class PRPairDataset(Dataset):
    "piano roll pair dataset"
    def __init__(self, 
            image_dataset_dir='~/datasets/POP909_images_basic', 
            crop_size=128, 
            max_shift_x=12, 
            max_shift_y=12,
            split='train',
            val_fraction=0.1,
            seed=42,
            verbose=True,
            sigma=7,               # param for truncnorm dist for sampling shifts/deltas
            shared=None,   # Possible shared memory thing for changing deets on the fly
            ):
        self.crop_size, self.max_shift_x, self.max_shift_y = crop_size, max_shift_x, max_shift_y
        self.sigma, self.shared = sigma, shared
        
        # Load and split filenames
        all_filenames = glob(os.path.join(os.path.expandvars(os.path.expanduser(image_dataset_dir)), '**/*.png'), recursive=True)
        rng = random.Random(seed)
        shuffled = all_filenames.copy()
        rng.shuffle(shuffled)
        split_idx = int(len(shuffled) * (1 - val_fraction))
        
        if split == 'train':
            self.filenames = shuffled[:split_idx]
        else:
            self.filenames = shuffled[split_idx:]
            
        self.actual_len = len(self.filenames)
        self.images = []
        if verbose: print(f"Loading {self.actual_len} {split} files from {image_dataset_dir}... ",end="")
        for f in self.filenames: 
            img = Image.open(f).convert('L')  # grayscale
            self.images.append((np.array(img, dtype=np.uint8) > 0).astype(np.uint8)) # binary uint8
        if verbose: print(f"Finished loading.")

    def __len__(self):
        return self.actual_len * 100  # arbitrary large number for epoch length

    def __getitem__(self, idx):
        # ignore idx, just randomly sample
        file_idx = random.randint(0, self.actual_len - 1)
        img = torch.from_numpy(self.images[file_idx]).float() 

        # augmentation in y: transpose entire img in y before doing aything else.
        aug_y = sample_shift(6, self.sigma)    # +/- six semitones data augmentation (shift_y may add +/- 12 more, below)
        img = shift_no_wrap(img, shifts=aug_y, dims=0)
         
        h, w = img.shape
        msx = self.shared['training']['max_shift_x'] if self.shared else self.max_shift_x
        msy = self.shared['training']['max_shift_y'] if self.shared else self.max_shift_y
        shift_x, shift_y = sample_shifts(msx, msy, self.sigma)

        # cropping
        # sample loc1 such that both crops are valid
        min_loc = max(0, -shift_x)
        max_loc = min(w - self.crop_size, w - self.crop_size - shift_x)
        loc1 = random.randint(min_loc, max_loc)
        loc2 = loc1 + shift_x
        
        # crop horizontally
        img1 = img[:, loc1:loc1 + self.crop_size]  # img1 is a random crop (augmentation)
        img2 = img[:, loc2:loc2 + self.crop_size]  # img2, rather than being img1+shift, is just cropped from a slightly different locationb        
        img2 = shift_no_wrap(img2, shifts=shift_y, dims=0)    # y-shifts (transposition)
        
        return {
            'img1': img1.unsqueeze(0),  # add channel dim (1, 128, 128)
            'img2': img2.unsqueeze(0),
            'deltas': torch.tensor([shift_x, shift_y], dtype=torch.float32).abs(),
            'file_idx': file_idx,
        }

# %% ../nbs/01_data.ipynb #13ba9ffc-51c2-4b85-b357-4e1ea53e0a23
SCHEME_NAMES = {  0: 'pitch-pitch',    1: 'time-time',        2: 'pitch-time'}
TARGET_NAMES = {1.0: 'parallel',    -1.0: 'anti-parallel',  0.0: 'orthogonal'}

class ShiftedTripletDataset(AnchorDataset):
    """Piano roll triplet dataset inheriting from AnchorDataset."""
    def __init__(self, 
            max_shift_x=12, 
            max_shift_y=12,
            shared=None,
            aug_y_max=6, 
            **kwargs,   # passes through to AnchorDataset.__init__
            ):
        super().__init__(aug_y_max=aug_y_max, **kwargs)
        self.max_shift_x, self.max_shift_y = max_shift_x, max_shift_y
        self.shared = shared

    def __getitem__(self, idx, requested_scheme=None, requested_target=None):
        # --- sample shifts sx1, sy1, sx2, sy2 from distribution
        msx = self.shared['training']['max_shift_x'] if self.shared else self.max_shift_x
        msy = self.shared['training']['max_shift_y'] if self.shared else self.max_shift_y
        while True:
            scheme = torch.randint(0, 3, (1,)).item() if requested_scheme is None else int(requested_scheme)
            if requested_target is not None and requested_target != 0: scheme = torch.randint(0, 2, (1,)).item()
            sign1 = 1 if torch.rand(1) > 0.5 else -1
            if requested_target is None: 
                sign2 = 1 if torch.rand(1) > 0.5 else -1
            else: 
                sign2 = sign1 * int(requested_target)
            if scheme == 0:    
                s1 = abs(sample_shift(msy, self.sigma)) or 1  # 0's are handled explicitly below according to scheme
                s2 = abs(sample_shift(msy, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = sign1*s1, 0, sign2*s2, 0    # both shift in y
            elif scheme == 1:  
                s1 = abs(sample_shift(msx, self.sigma)) or 1
                s2 = abs(sample_shift(msx, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = 0, sign1*s1, 0, sign2*s2    # both shifts in x
            else:                                                
                s1 = abs(sample_shift(msy, self.sigma)) or 1
                s2 = abs(sample_shift(msx, self.sigma)) or 1
                dy1, dx1, dy2, dx2 = sign1*s1, 0, 0, sign2*s2 # first one y, second one x
            if not ((dy1==dy2) and (dx1==dx2)) and not (dx1==0 and dy1==0) and not (dx2==0 and dy2==0): break 
        target = float(np.sign(sign1 * sign2)) if scheme < 2 else 0.0   
        if requested_target is not None and torch.abs(target-requested_target) > 1e-3: 
            raise UserWarning(f"Warning: requested_target = {requested_target}, but got target = {target}")
        # --- Now we know what shifts we want to do, next let's construct the crops.

        # obtain the wider anchor, with sufficient padding later crops
        pad_x = ( abs(min(min(dx1,dx2), 0)), max(max(dx1, dx2), 0) ) 
        anchor = super().__getitem__(idx, pad_x=pad_x)
        img = anchor['img']  # (1, H, crop_size + 2*sx)  <-- note the extra "1," for what follows!
        cs = self.crop_size if isinstance(self.crop_size, int) else self.crop_size[1]  # width dimension

        # crops in x
        c1 = img[:,:, pad_x[0]+dx1: pad_x[0]+dx1+cs]
        c2 = img[:,:, pad_x[0]+dx2: pad_x[0]+dx2+cs]
        img = img[:,:,pad_x[0]:     pad_x[0]+cs]       # crop anchor to final size

        # shift c1 and c2 images in y 
        c1 = shift_no_wrap(c1, shifts=dy1, dims=1) 
        c2 = shift_no_wrap(c2, shifts=dy2, dims=1)
        return {
            'img1': img, 'img2': c1, 'img3': c2,
            'deltas': torch.tensor([[dy1,dx1],[dy2,dx2]], dtype=torch.int),
            'file_idx': anchor['file_idx'], 'scheme': scheme, 'target': torch.tensor(target),
        }

# %% ../nbs/01_data.ipynb #510bad1c
class PreEncodedChunkDataset(Dataset):
    """Lazy-loading dataset for preencode chunk files (list-of-batch-dicts format).
    Each chunk is a list of dicts with emb keys (list of level tensors, each (B,N,D))
    and optionally img keys ((B,C,H,W) bool). Flattens to individual samples.

    Args:
        encoded_dir: directory containing {split}_chunk*.pt files
        split:       'train' or 'val'
        emb_key:     which embedding to return ('emb1', 'emb2', 'emb3')
        img_key:     which image to return ('img1', etc.), or None to omit images

    Returns (emb_levels, img) tuples, or just emb_levels when img_key=None."""
    def __init__(self, encoded_dir, split='train', emb_key='emb1', img_key='img1'):
        self.emb_key, self.img_key = emb_key, img_key
        encoded_dir = os.path.expandvars(os.path.expanduser(str(encoded_dir)))
        self.files = sorted(glob(os.path.join(encoded_dir, f'{split}_chunk*.pt')))
        assert self.files, f"No {split}_chunk*.pt files in {encoded_dir}"
        self.index = []
        self.chunk_sample_ranges = {}
        for ci, f in enumerate(self.files):
            chunk = torch.load(f, map_location='cpu', weights_only=False)
            start = len(self.index)
            for ri, rec in enumerate(chunk):
                for si in range(rec[emb_key][0].shape[0]):
                    self.index.append((ci, ri, si))
            self.chunk_sample_ranges[ci] = (start, len(self.index))
            del chunk
        self._cache_ci = None
        self._cache_data = None

    def __len__(self): return len(self.index)

    def __getitem__(self, idx):
        ci, ri, si = self.index[idx]
        if ci != self._cache_ci:
            self._cache_data = torch.load(self.files[ci], map_location='cpu', weights_only=False)
            self._cache_ci = ci
        rec = self._cache_data[ri]
        emb = [lvl[si].float() for lvl in rec[self.emb_key]]
        if self.img_key is None: return emb
        return emb, rec[self.img_key][si].float()


class ChunkShuffleSampler(Sampler):
    """Shuffle chunk order each epoch; access items within each chunk sequentially.
    Prevents DataLoader workers from thrashing between chunks."""
    def __init__(self, dataset, shuffle=True):
        self.dataset = dataset
        self.shuffle = shuffle

    def __len__(self): return len(self.dataset)

    def __iter__(self):
        n = len(self.dataset.files)
        order = torch.randperm(n).tolist() if self.shuffle else list(range(n))
        indices = []
        for ci in order:
            s, e = self.dataset.chunk_sample_ranges[ci]
            indices.extend(range(s, e))
        return iter(indices)


def collate_emb_levels(batch):
    "Stack per-sample level embeddings (list of (N,D) tensors), padding variable-N to max."
    n_levels = len(batch[0])
    result = []
    for lev in range(n_levels):
        tensors = [item[lev] for item in batch]
        max_n = max(t.shape[0] for t in tensors)
        padded = []
        for t in tensors:
            if t.shape[0] < max_n:
                t = torch.cat([t, torch.zeros(max_n - t.shape[0], *t.shape[1:], dtype=t.dtype)], 0)
            padded.append(t)
        result.append(torch.stack(padded))
    return result


def collate_preencode(batch):
    "Collate (emb_levels, img) pairs from PreEncodedChunkDataset."
    return collate_emb_levels([b[0] for b in batch]), torch.stack([b[1] for b in batch])


def get_pos_cache(encoder, image_size, device):
    "Run encoder on a dummy input to extract the fixed per-level positional grid."
    dummy = torch.zeros(1, 1, image_size, image_size, device=device)
    with torch.no_grad():
        enc_out = encoder(dummy)
    return [lvl.pos.squeeze(0) for lvl in enc_out.patches.levels]


def emb_levels_to_enc_out(emb_levels, pos_cache, device):
    "Assemble a minimal EncoderOutput from stored emb level tensors and a pos cache."
    levels = [PatchState(emb=emb.to(device), pos=pos_cache[i], non_empty=None, mae_mask=None)
              for i, emb in enumerate(emb_levels)]
    return EncoderOutput(patches=HierarchicalPatchState(levels=levels),
                         full_pos=None, full_non_empty=None, mae_mask=None)

# %% ../nbs/01_data.ipynb #i4isbzdempl
class EmbeddingDataset(Dataset):
    """Load PCA-projected embeddings from chunk files produced by fit_pca.

    Each chunk file is a dict with keys 'L0', 'L1', ... each (N_chunk, D) or (N_chunk, P, D).
    Optionally loads raw preencode chunks (list of batch dicts) for the no-PCA path.

    Args:
        paths:   glob pattern, Path, or list thereof pointing to chunk .pt files
        levels:  list of level keys to use, e.g. ['L0','L1',...,'L5'].
                 If multiple levels given, concatenates along dim=1.
                 If None, uses all keys found in the first file.
        key:     for raw preencode chunks, which embedding key ('emb1','emb2','emb3')
        level:   for raw preencode chunks, which hierarchy level index
    """
    def __init__(self, paths, levels=None, key='emb2', level=0):
        import glob as _glob
        if isinstance(paths, (str, Path)): paths = [paths]
        all_files = []
        for p in paths:
            expanded = sorted(_glob.glob(os.path.expandvars(os.path.expanduser(str(p)))))
            all_files.extend([Path(x) for x in expanded] if expanded else [Path(p)])

        all_embs = []
        for fp in all_files:
            data = torch.load(fp, weights_only=False)
            if isinstance(data, dict) and any(k.startswith("L") for k in data):
                # PCA chunk format: {'L0': (N,D) or (N,P,D), 'L1': ...}
                lvls = levels or sorted(k for k in data if k.startswith("L"))
                tensors = [data[lv].float() for lv in lvls]
                tensors = [t.flatten(1) if t.dim() == 3 else t for t in tensors]  # (N,P,D) → (N,P*D)
                if not hasattr(self, '_level_dims'):
                    self._level_dims = [t.shape[1] for t in tensors]
                all_embs.append(torch.cat(tensors, dim=1) if len(tensors) > 1 else tensors[0])
            elif isinstance(data, list):
                # Raw preencode chunk format
                for batch_rec in data:
                    emb = batch_rec[key][level]      # (B, N_patches, D)
                    all_embs.append(emb.flatten(1).float())
            else:
                raise ValueError(f"Unrecognised format in {fp}")
        self.embeddings = torch.cat(all_embs, dim=0)
        self.level_dims = getattr(self, '_level_dims', [self.embeddings.shape[1]])

    def __len__(self): return len(self.embeddings)
    def __getitem__(self, i): return self.embeddings[i]

# %% ../nbs/01_data.ipynb #jflcahvd7s
import bisect

class ConditionalFlowDataset(Dataset):
    """Paired dataset for training ConditionalFineFlowModel.

    Returns (x_coarse, x_fine) pairs where:
      x_coarse : flat PCA-compressed coarse levels  — matches first-stage flow output
      x_fine   : flat PCA-compressed fine levels

    Unified mode (preferred): pca_dir contains {split}_chunk*_pca.pt files with all
    levels (L0-L5) as keys. Coarse and fine are loaded from the same files in one pass.

    Legacy mode: pca_dir has *_pca20.pt (coarse) + fine_pca_dir has *_fine_pca*.pt (fine).

    Args:
        pca_dir:          directory with PCA chunk files (unified *_pca.pt or legacy *_pca20.pt)
        encoded_dir:      raw encoded dir; required only for legacy lazy-load fine mode
        pca_levels:       coarse level keys to load, default ['L0','L1','L2','L3']
        fine_levels:      fine level indices, default [4, 5]
        emb_key:          embedding key for raw encoded chunks, default 'emb1'
        split:            'train' or 'val'
        fine_pca_dir:     legacy: directory with *_fine_pca*.pt files
        fine_n_components: legacy: int or list; determines suffix for fine_pca files
    """
    def __init__(self, pca_dir, encoded_dir=None, pca_levels=None, fine_levels=None,
                 emb_key='emb1', split='train', fine_pca_dir=None, fine_n_components=None,
                 fine_raw=False):
        import glob as _glob
        pca_dir    = os.path.expandvars(os.path.expanduser(str(pca_dir)))
        pca_levels = pca_levels or ['L0', 'L1', 'L2', 'L3']
        fine_levels = fine_levels or [4, 5]

        self._fine_levels = fine_levels
        self._emb_key     = emb_key

        # Detect unified vs legacy format
        unified_files = sorted(_glob.glob(os.path.join(pca_dir, f'{split}_chunk*_pca.pt')))
        use_unified   = len(unified_files) > 0

        if use_unified:
            pca_files = unified_files
            if fine_raw:
                use_unified = False   # coarse loads from pca_files; fine will use raw embeddings
        else:
            pca_files = sorted(_glob.glob(os.path.join(pca_dir, f'{split}_chunk*_pca20.pt')))
        assert pca_files, f"No {split}_chunk*_pca.pt or *_pca20.pt in {pca_dir}"

        # Load coarse (and fine in unified mode) upfront
        print(f"  Loading {'unified' if use_unified else 'coarse'} PCA data ({len(pca_files)} chunks)...", flush=True)
        coarse_all = []
        fine_all_unified = [] if use_unified else None
        self._chunk_offsets = [0]

        for pf in pca_files:
            pca_data = torch.load(pf, weights_only=False)

            # Coarse levels — record n_comp and n_patches before flattening
            coarse_tensors = [pca_data[lv].float() for lv in pca_levels]
            if not hasattr(self, '_coarse_n_comp'):
                self._coarse_n_comp    = [t.shape[-1] for t in coarse_tensors]
                self._coarse_n_patches = [t.shape[-2] if t.dim() == 3 else 1 for t in coarse_tensors]
            coarse_tensors = [t.flatten(1) if t.dim() == 3 else t for t in coarse_tensors]
            if not hasattr(self, '_coarse_level_dims'):
                self._coarse_level_dims = [t.shape[1] for t in coarse_tensors]
            coarse_chunk = torch.cat(coarse_tensors, dim=1)
            coarse_all.append(coarse_chunk)
            self._chunk_offsets.append(self._chunk_offsets[-1] + len(coarse_chunk))

            # Fine levels (unified mode only) — record n_comp before flattening
            if use_unified:
                fine_tensors = [pca_data[f'L{li}'].float() for li in fine_levels]
                if not hasattr(self, '_fine_n_comp'):
                    self._fine_n_comp    = [t.shape[-1] for t in fine_tensors]
                    self._fine_n_patches = [t.shape[-2] if t.dim() == 3 else 1 for t in fine_tensors]
                fine_tensors = [t.flatten(1) if t.dim() == 3 else t for t in fine_tensors]
                if not hasattr(self, '_fine_level_dims'):
                    self._fine_level_dims = [t.shape[1] for t in fine_tensors]
                fine_all_unified.append(torch.cat(fine_tensors, dim=1))

        self.coarse = torch.cat(coarse_all, dim=0)
        print(f"  Coarse loaded: {len(self.coarse)} samples, {self.coarse.shape[1]} dims", flush=True)
        self.coarse_level_dims = self._coarse_level_dims
        self.coarse_n_comp     = self._coarse_n_comp     # PCA components per patch per coarse level
        self.coarse_n_patches  = self._coarse_n_patches  # patches per coarse level

        if use_unified:
            self.fine = torch.cat(fine_all_unified, dim=0)
            print(f"  Fine loaded: {len(self.fine)} samples, {self.fine.shape[1]} dims", flush=True)
            self._use_fine_pca = True

        elif fine_pca_dir is not None:
            # Legacy: load fine from separate *_fine_pca*.pt files
            assert fine_n_components is not None, "fine_n_components required when fine_pca_dir is set"
            fine_pca_dir = os.path.expandvars(os.path.expanduser(str(fine_pca_dir)))
            if isinstance(fine_n_components, int):
                fn_suffix = f"fine_pca{fine_n_components}"
            else:
                fn_suffix = "fine_pca" + "_".join(str(n) for n in fine_n_components)
            fine_files = sorted(_glob.glob(os.path.join(fine_pca_dir, f'{split}_chunk*_{fn_suffix}.pt')))
            assert fine_files, f"No {split}_chunk*_{fn_suffix}.pt in {fine_pca_dir}"
            assert len(fine_files) == len(pca_files), \
                f"Chunk count mismatch: {len(pca_files)} coarse vs {len(fine_files)} fine"
            print(f"  Loading fine PCA data ({len(fine_files)} chunks, {fn_suffix})...", flush=True)
            fine_all = []
            for fp in fine_files:
                fd = torch.load(fp, weights_only=False)
                tensors = [fd[f'L{li}'].float() for li in fine_levels]
                if not hasattr(self, '_fine_n_comp'):
                    self._fine_n_comp    = [t.shape[-1] for t in tensors]
                    self._fine_n_patches = [t.shape[-2] if t.dim() == 3 else 1 for t in tensors]
                tensors = [t.flatten(1) if t.dim() == 3 else t for t in tensors]
                if not hasattr(self, '_fine_level_dims'):
                    self._fine_level_dims = [t.shape[1] for t in tensors]
                fine_all.append(torch.cat(tensors, dim=1))
            self.fine = torch.cat(fine_all, dim=0)
            print(f"  Fine loaded: {len(self.fine)} samples, {self.fine.shape[1]} dims", flush=True)
            self._use_fine_pca = True

        else:
            # Legacy lazy-load from raw encoded_dir
            assert encoded_dir is not None, "encoded_dir required when fine_pca_dir is not set"
            encoded_dir = os.path.expandvars(os.path.expanduser(str(encoded_dir)))
            raw_files = sorted(_glob.glob(os.path.join(encoded_dir, f'{split}_chunk*.pt')))
            raw_files = [f for f in raw_files if not f.endswith('_pca20.pt')]
            assert raw_files, f"No {split}_chunk*.pt in {encoded_dir}"
            assert len(pca_files) == len(raw_files), \
                f"Chunk count mismatch: {len(pca_files)} pca vs {len(raw_files)} raw"
            self._raw_files = raw_files
            raw0 = torch.load(raw_files[0], weights_only=False)
            _raw_embs = [raw0[0][emb_key][li].float() for li in fine_levels]
            self._fine_n_patches  = [e.shape[1] for e in _raw_embs]   # n_patches per level
            self._fine_n_comp     = [e.shape[2] for e in _raw_embs]   # embed_dim per patch
            self._fine_level_dims = [np * nc for np, nc in
                                     zip(self._fine_n_patches, self._fine_n_comp)]
            del raw0, _raw_embs
            self._use_fine_pca    = False
            self._fine_chunk_idx  = -1
            self._fine_chunk_data = None

        self.fine_level_dims = self._fine_level_dims
        self.fine_n_comp     = self._fine_n_comp     # PCA components per patch per fine level
        self.fine_n_patches  = self._fine_n_patches  # patches per fine level

    def _load_fine_chunk(self, chunk_idx):
        if self._fine_chunk_idx == chunk_idx:
            return
        raw_data = torch.load(self._raw_files[chunk_idx], weights_only=False)
        fine_lvls = []
        for batch_rec in raw_data:
            lvl_tensors = [batch_rec[self._emb_key][li].float() for li in self._fine_levels]
            fine_lvls.append(torch.cat([t.flatten(1) for t in lvl_tensors], dim=1))
        self._fine_chunk_data = torch.cat(fine_lvls, dim=0)
        self._fine_chunk_idx  = chunk_idx

    def __len__(self): return len(self.coarse)

    def __getitem__(self, i):
        if self._use_fine_pca:
            return self.coarse[i], self.fine[i]
        chunk_idx = bisect.bisect_right(self._chunk_offsets, i) - 1
        self._load_fine_chunk(chunk_idx)
        local_i = i - self._chunk_offsets[chunk_idx]
        return self.coarse[i], self._fine_chunk_data[local_i]


class ConditionalFlowChunkSampler(torch.utils.data.Sampler):
    """Yields indices chunk-by-chunk in shuffled order, with within-chunk shuffle.

    Use instead of shuffle=True in the DataLoader when the dataset loads
    fine data lazily per chunk — this ensures each chunk is loaded once
    per epoch rather than being thrashed by fully random access.
    """
    def __init__(self, dataset: ConditionalFlowDataset, generator=None):
        self.offsets   = dataset._chunk_offsets   # [0, N0, N0+N1, ...]
        self.generator = generator

    def __len__(self):
        return self.offsets[-1]

    def __iter__(self):
        n_chunks = len(self.offsets) - 1
        chunk_order = torch.randperm(n_chunks, generator=self.generator).tolist()
        for ci in chunk_order:
            start, end = self.offsets[ci], self.offsets[ci + 1]
            within = torch.randperm(end - start, generator=self.generator) + start
            yield from within.tolist()
