"""(Notebooke only) Interactive exploration of trained encoder and embeddings"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_inspect.ipynb.

# %% auto #0
__all__ = ['svd_metrics', 'factorization_metrics', 'equivariance_r2', 'eval_encoder']

# %% ../nbs/07_inspect.ipynb #aabb0002
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

# %% ../nbs/07_inspect.ipynb #aabb0003
def svd_metrics(enc_out, level=0):
    "Compute SVD scalar metrics (no plots) at given hierarchy level. level=0 is coarsest (CLS)."
    z = enc_out.patches[level].emb.detach().cpu().float().reshape(-1, enc_out.patches[level].dim)
    z = z - z.mean(dim=0)
    _, S, _ = torch.linalg.svd(z, full_matrices=False)
    var_exp = (S**2) / (S**2).sum()
    n90 = int((var_exp.cumsum(0) < 0.9).sum().item()) + 1
    # Spectral SNR (eigengap): ratio of weakest signal eigenvalue to strongest noise eigenvalue
    # λ_i ∝ S_i^2; r = n90; SNR = λ_r / λ_{r+1} (G2G Section 7.3)
    spectral_snr = (S[n90-1]**2 / S[n90]**2).item() if n90 < len(S) else float('inf')
    return {'n90': n90, 'top1_var': var_exp[0].item(), 'spectral_snr': spectral_snr, 'S': S, 'var_exp': var_exp}

# %% ../nbs/07_inspect.ipynb #aabb0004
def factorization_metrics(encoder, cfg, device='cpu', batch_size=256, n_batches=10):
    "Compute pitch-time factorization cosine metrics per level. Returns flat dict of scalars."
    from midi_rae.data import ShiftedTripletDataset
    ds = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split='val',
                               max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y)
    subset = torch.utils.data.Subset(ds, range(batch_size * n_batches))
    dl = DataLoader(subset, batch_size=batch_size, shuffle=False, num_workers=2)
    encoder.eval()
    d2_vecs, d3_vecs, targets, schemes = None, None, [], []
    for i, batch in enumerate(dl):
        img1, img2, img3 = batch['img1'].to(device), batch['img2'].to(device), batch['img3'].to(device)
        targets.append(batch['target'].squeeze(-1)); schemes.append(batch['scheme'].squeeze(-1))
        with torch.no_grad():
            enc_out1, enc_out2, enc_out3 = encoder(img1), encoder(img2), encoder(img3)
        z1 = [lvl.emb for lvl in enc_out1.patches.levels]
        z2 = [lvl.emb for lvl in enc_out2.patches.levels]
        z3 = [lvl.emb for lvl in enc_out3.patches.levels]
        n_levels = enc_out1.patches.num_levels
        if d2_vecs is None: d2_vecs, d3_vecs = [[] for _ in range(n_levels)], [[] for _ in range(n_levels)]
        for lev in range(n_levels):
            d2_vecs[lev].append((z2[lev]-z1[lev]).mean(dim=1).cpu())
            d3_vecs[lev].append((z3[lev]-z1[lev]).mean(dim=1).cpu())
    targets = torch.cat(targets, dim=0); schemes = torch.cat(schemes, dim=0)
    metrics = {}
    for lev in range(n_levels):
        d2, d3 = torch.cat(d2_vecs[lev], dim=0), torch.cat(d3_vecs[lev], dim=0)
        s0, s1, s2 = schemes == 0, schemes == 1, schemes == 2
        pitch_d = torch.cat([d2[s0], d3[s0], d2[s2]], dim=0)
        time_d  = torch.cat([d2[s1], d3[s1], d3[s2]], dim=0)
        par  = (s0|s1) & (targets > 0.5)
        anti = (s0|s1) & (targets < -0.5)
        n_min = min(len(pitch_d), len(time_d))
        metrics[f'L{lev}_cross']    = F.cosine_similarity(pitch_d[:n_min], time_d[:n_min], dim=-1).mean().item()
        metrics[f'L{lev}_parallel'] = F.cosine_similarity(d2[par],  d3[par],  dim=-1).mean().item() if par.any()  else float('nan')
        metrics[f'L{lev}_anti']     = F.cosine_similarity(d2[anti], d3[anti], dim=-1).mean().item() if anti.any() else float('nan')
    return metrics

# %% ../nbs/07_inspect.ipynb #aabb0007
def equivariance_r2(encoder, cfg, device='cpu', batch_size=256, n_batches=10):
    """Compute R² equivariance metrics per level.
    For a perfectly equivariant encoder: pitch/time R²≈1, cross R²≈0.
    deltas shape from ShiftedTripletDataset: (B, 2, 2) = (B, [d2,d3], [pitch,time])."""
    from midi_rae.data import ShiftedTripletDataset
    from sklearn.decomposition import PCA
    from sklearn.linear_model import LinearRegression
    import numpy as np
    ds = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split='val',
                               max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y)
    subset = torch.utils.data.Subset(ds, range(batch_size * n_batches))
    dl = DataLoader(subset, batch_size=batch_size, shuffle=False, num_workers=2)
    encoder.eval()
    pitch_diffs, time_diffs = None, None
    for batch in dl:
        img1, img2, img3 = batch['img1'].to(device), batch['img2'].to(device), batch['img3'].to(device)
        deltas = batch['deltas']   # (B, 2, 2): [d2,d3] x [pitch,time]
        schemes = batch['scheme'].squeeze(-1)
        s0, s1, s2 = schemes == 0, schemes == 1, schemes == 2
        with torch.no_grad():
            enc_out1, enc_out2, enc_out3 = encoder(img1), encoder(img2), encoder(img3)
        z1 = [lvl.emb for lvl in enc_out1.patches.levels]
        z2 = [lvl.emb for lvl in enc_out2.patches.levels]
        z3 = [lvl.emb for lvl in enc_out3.patches.levels]
        n_levels = enc_out1.patches.num_levels
        if pitch_diffs is None:
            pitch_diffs = [[] for _ in range(n_levels)]
            time_diffs  = [[] for _ in range(n_levels)]
        for lev in range(n_levels):
            d2 = (z2[lev]-z1[lev]).mean(dim=1).cpu()
            d3 = (z3[lev]-z1[lev]).mean(dim=1).cpu()
            # pitch diffs: scheme 0 gives both d2,d3; scheme 2 gives d2
            p_diffs = torch.cat([d2[s0], d3[s0], d2[s2]], dim=0)
            p_mags  = torch.cat([deltas[s0,0,0], deltas[s0,1,0], deltas[s2,0,0]], dim=0).float()
            # time diffs: scheme 1 gives both d2,d3; scheme 2 gives d3
            t_diffs = torch.cat([d2[s1], d3[s1], d3[s2]], dim=0)
            t_mags  = torch.cat([deltas[s1,0,1], deltas[s1,1,1], deltas[s2,1,1]], dim=0).float()
            pitch_diffs[lev].append((p_diffs, p_mags))
            time_diffs[lev].append((t_diffs, t_mags))
    metrics = {}
    for lev in range(n_levels):
        p_d = torch.cat([x[0] for x in pitch_diffs[lev]], dim=0).numpy()
        p_m = torch.cat([x[1] for x in pitch_diffs[lev]], dim=0).numpy().reshape(-1,1)
        t_d = torch.cat([x[0] for x in time_diffs[lev]],  dim=0).numpy()
        t_m = torch.cat([x[1] for x in time_diffs[lev]],  dim=0).numpy().reshape(-1,1)
        pitch_axis = PCA(n_components=1).fit(p_d).components_[[0]].T  # (D,1)
        time_axis  = PCA(n_components=1).fit(t_d).components_[[0]].T  # (D,1)
        def r2(X, y): return LinearRegression().fit(X, y).score(X, y)
        metrics[f'L{lev}_r2_pitch']    = r2(p_d @ pitch_axis, p_m)  # want ≈1
        metrics[f'L{lev}_r2_time']     = r2(t_d @ time_axis,  t_m)  # want ≈1
        metrics[f'L{lev}_r2_cross_pt'] = r2(p_d @ time_axis,  p_m)  # want ≈0
        metrics[f'L{lev}_r2_cross_tp'] = r2(t_d @ pitch_axis, t_m)  # want ≈0
    return metrics

# %% ../nbs/07_inspect.ipynb #aabb0005
def eval_encoder(cfg, encoder, device='cpu', batch_size=256):
    "Run all scalar eval metrics on a trained encoder. Returns flat dict."
    from midi_rae.data import ShiftedTripletDataset
    ds = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split='val',
                               max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y)
    dl = DataLoader(ds, batch_size=batch_size, drop_last=True, num_workers=2)
    batch = next(iter(dl))
    with torch.no_grad():
        with torch.autocast(device_type=device, dtype=torch.bfloat16):
            enc_out = encoder(batch['img2'].to(device))
    metrics = {}
    for lev in range(enc_out.patches.num_levels):
        m = svd_metrics(enc_out, level=lev)
        metrics[f'svd_L{lev}_n90']         = m['n90']
        metrics[f'svd_L{lev}_top1_var']    = m['top1_var']
        metrics[f'svd_L{lev}_spectral_snr'] = m['spectral_snr']
    metrics.update(factorization_metrics(encoder, cfg, device=device, batch_size=batch_size))
    metrics.update(equivariance_r2(encoder, cfg, device=device, batch_size=batch_size))
    return metrics
