"""LeJEPA, GAN discriminator, ...aand more"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_losses.ipynb.

# %% auto #0
__all__ = ['safe_mean', 'SIGReg', 'attraction_loss', 'factorization_loss', 'LeJEPA', 'calc_mae_loss', 'anchor_loss',
           'calc_enc_loss', 'calc_enc_loss_multiscale', 'PatchGANDiscriminator', 'calc_dec_loss']

# %% ../nbs/03_losses.ipynb #b96051a7
import torch
import torch.nn as nn
import torch.nn.functional as F 
import math

# %% ../nbs/03_losses.ipynb #59c62704
def safe_mean(t, dim=None): 
    """safe replacement for torch.mean( ).  can't be used as a suffix though"""
    return t.mean(dim=dim) if t.numel() > 0 else 0.0

# %% ../nbs/03_losses.ipynb #a164c279
def SIGReg(x, global_step, num_slices=256, chunk_size=32):
    """SIGReg with Epps-Pulley statistic. x is (N, K) tensor.
       Chunked to reduce memory pressure -> More GPU utilization. :-)"""
    with torch.amp.autocast('cuda', enabled=False): # accum in float32
        x = x.float()
        device = x.device
        g = torch.Generator(device=device).manual_seed(global_step)
        A = torch.randn((x.size(1), num_slices), generator=g, device=device)
        A = A / (A.norm(dim=0, keepdim=True) + 1e-10)
        t = torch.linspace(-5, 5, 17, device=device)
        exp_f = torch.exp(-0.5 * t**2)
        T_total = torch.tensor(0.0, device=device)    # float32 accumulator
        if chunk_size < 1: chunk_size = num_slices    # < 1 Turns off chunking
        for i in range(0, num_slices, chunk_size):
            x_t = (x @ A[:, i:i+chunk_size]).unsqueeze(2) * t  # (N, chunk, T)
            ecf = (torch.exp(1j * x_t).mean(dim=0)).abs()
            diff = (ecf - exp_f).abs().square().mul(exp_f)
            T_total = T_total + torch.trapz(diff, t, dim=1).sum()
        return T_total

# %% ../nbs/03_losses.ipynb #cf61d695
# The first attraction loss I started with; has an exponential fall off in distance.
# def attraction_loss_old(z1, z2,        # embeddings of two "views" of the same thing (in batches)
#                     deltas=None,   # optional/TBD: info on semantic 'distance' between z1 & z2
#                     psize=None,    # patch_size (patch_w, patch_h)
#                     tau = 100.0,   # inverse strength of fall-off weighting for delta distances, big=slower
#                     freq_scale=True, # whether to do joint non-empty frequency normalization
#                     zero_outside_receptive_field=True, 
#                     ):   
#     "How we pull similar 'views' together"
#     if deltas is None: return safe_mean( (z1 - z2).square() )
#     delta_diag = (deltas**2).sum(dim=1)
#     delta_fac = torch.exp(-delta_diag / tau) # less attraction for more 'distant' views
#     #delta_fac = 1/(1 + delta_diag/tau)  # longer tail than exp
#     if psize is not None:
#         if freq_scale: delta_fac = delta_fac * math.sqrt((32./psize[0])*(32./psize[1]))  # joint-non-empty frequency normalization (scales per refinement)
#         if zero_outside_receptive_field and psize[0]==4: 
#             delta_fac[(deltas[:,0].abs() >= psize[0]) | (deltas[:,1].abs() >= psize[1])] = 0 # zero out cases where shift >= patch size 
#         #delta_fac = (1 - deltas[:,0].abs()/psize[0]).clamp(min=0) * (1 - deltas[:,1].abs()/psize[1]).clamp(min=0)  # "overlap weighting": bilinear falloff (to zero if shift >= psize)
#     return safe_mean( (z1 - z2).square() * delta_fac.unsqueeze(-1) )


def attraction_loss(z1, z2,        # embeddings of two "views" of the same thing (in batches)
                    deltas=None,   # optional/TBD: info on semantic 'distance' between z1 & z2
                    alpha = 1.0,   # scaled margin strenth 
                    **kwargs,      # unused stuff, kept for compatibility of calling sequence with other attr losses
                    ):   
    "Pull similar 'views' together, but with delta-scaled margin to prevent over-collapse"
    if deltas is None: return safe_mean( (z1 - z2).square() )
    dist = (z1 - z2).norm(dim=-1)
    delta_diag = (deltas**2).sum(dim=1)
    margin = alpha * delta_diag.sqrt() 
    return safe_mean( (dist - margin).clamp(min=0).square() )

# %% ../nbs/03_losses.ipynb #3a9a0faf-a370-4410-84df-5e7e63f9ec65
def factorization_loss(z_anchor, z_crop1, z_crop2, targets):
    # To encourage "soft" factorization/decomposition in pitch vs time.  
    # See post   https://drscotthawley.github.io/blog/posts/FactorizingSoftly.html
    # where targets are +1 (same-type, same-sign), −1 (same-type, opposite-sign), or 0 (cross-type):
    d1 = z_crop1 - z_anchor
    d2 = z_crop2 - z_anchor
    cos = F.cosine_similarity(d1, d2, dim=-1)
    return safe_mean((cos - targets) ** 2)

# %% ../nbs/03_losses.ipynb #624570b6
def LeJEPA(z1, z2, global_step, z3=None, targets=None, lambd=0.5, deltas=None, psize=None, sigreg_on_both=True, sigreg_prefac=0.5, lambda_fac=0.5): 
    "Main LeJEPA loss function"
    sim = attraction_loss(z1, z2, deltas=deltas, psize=psize)
    # design decision! ignore z1 for sigreg to make things more consistent when A/B'ing the use of the EMA encoder.
    if z3 is not None:   
        sigreg = SIGReg( torch.cat((z2, z3), dim=0) , global_step ) * sigreg_prefac  
        fact = factorization_loss(z1, z2, z3, targets)
        return {'loss': (1-lambd)*(sim + lambda_fac*fact) + lambd*sigreg, 
                'sim':sim.item(), 'sigreg':sigreg.item(), 'fact':fact.item()}
    else: 
        sigreg = SIGReg(z2, global_step ) * sigreg_prefac  
    return {'loss': (1-lambd)*sim + lambd*sigreg, 'sim':sim.item(), 'sigreg':sigreg.item()}

# %% ../nbs/03_losses.ipynb #34ecc897
def calc_mae_loss(recon_patches, img, enc_out, lambda_visible=0.1):
    "BCE loss on reconstructed patches, with optional downweighting of visible patches"     
    mae_mask = enc_out.mae_mask
    patch_size = int(recon_patches.shape[-1] ** 0.5)
    if mae_mask.dim() == 1: mae_mask = mae_mask[1:]  # strip CLS (ViT only)
    img_patches = img.unfold(2, patch_size, patch_size).unfold(3, patch_size, patch_size)
    img_patches = img_patches.flatten(2, 3).flatten(-2, -1).squeeze(1)  # (B, N, ps*ps)
    weights = torch.ones_like(recon_patches)
    weights[mae_mask] = lambda_visible  # works for both (N,) and (B,N)
    loss = (F.binary_cross_entropy_with_logits(recon_patches, img_patches, reduction='none') * weights).mean()
    return loss

# %% ../nbs/03_losses.ipynb #3fa01fc2
def anchor_loss(z1, z2):
    "Anchor embeddings of empty patches to the origin"
    return safe_mean( z1.square() ) + safe_mean( z2.square() )

# %% ../nbs/03_losses.ipynb #5a89c2b1
def calc_enc_loss(z1, z2, global_step, deltas=None, lambd=0.5, non_emptys=(None,None), lambda_anchor=0.05, psize=None):
    "Main loss function for Encoder"
    non_empty1, non_empty2 = non_emptys
    non_empty = non_empty1 & non_empty2  # both non-empty
    valid = non_empty.view(-1).bool()
    loss_dict = LeJEPA( z1[valid], z2[valid], global_step, deltas=deltas[valid], lambd=lambd, psize=psize )
    if lambda_anchor > 0:
        loss_dict['anchor'] = anchor_loss(z1[~non_empty1.view(-1).bool()], z2[~non_empty2.view(-1).bool()])
        loss_dict['loss'] = loss_dict['loss'] + lambda_anchor * loss_dict['anchor'] 
    return loss_dict

# %% ../nbs/03_losses.ipynb #3f4e797d-27b0-44de-be77-e68469aff268
@torch.compiler.disable
def calc_enc_loss_multiscale(z1, z2, global_step, img_size, deltas=None,
                             lambd=0.5, non_emptys=None, lambda_anchor=0.05):
    """Compute encoder loss at each hierarchy level of the Swin encoder. really really this time"""
    if not isinstance(z1, list):  # regular ViT
        d_exp = deltas.repeat_interleave(z1.shape[0] // deltas.shape[0], dim=0)
        return calc_enc_loss(z1.float(), z2.float(), global_step, deltas=d_exp.float(),
                             lambd=lambd, non_emptys=non_emptys, lambda_anchor=lambda_anchor)
    total = {}
    n_levels = len(z1)
    a_sum = a_count = 0.0
    level_losses = []
    for lev, (z1_l, z2_l, ne) in enumerate(zip(z1, z2, non_emptys)):
        B, N, D = z1_l.shape
        grid = int(N ** 0.5)  # TODO: assumes square images
        psize = (img_size // grid, img_size // grid)
        d_expanded = deltas.repeat_interleave(N, dim=0).float()
        z1_flat, z2_flat =      ( x.reshape(-1, D).float() for x in (z1_l,  z2_l))
        ne_flat          = tuple( x.reshape(-1).bool()     for x in (ne[0], ne[1]))  # non-emptys
        ld = calc_enc_loss(z1_flat, z2_flat, global_step, deltas=d_expanded,
                           lambd=lambd, non_emptys=ne_flat, lambda_anchor=lambda_anchor, psize=psize)
        level_losses.append({k: v.item() if hasattr(v, 'item') else v for k, v in ld.items()})
        for k, v in ld.items(): total[k] = total.get(k, 0) + v

    if not total: return {'loss': torch.tensor(0.0, device=deltas.device)}
    total = {k: v / n_levels for k, v in total.items()}
    total['levels'] = level_losses
    return total

# %% ../nbs/03_losses.ipynb #ade84ead
class PatchGANDiscriminator(nn.Module):
    def __init__(self, in_ch=1, base_ch=64, n_layers=3, use_spectral_norm=True):
        super().__init__()
        norm = nn.utils.spectral_norm if use_spectral_norm else (lambda x: x)
        layers = [norm(nn.Conv2d(in_ch, base_ch, kernel_size=4, stride=2, padding=1)), nn.LeakyReLU(0.2, True)]
        ch = base_ch
        for i in range(1, n_layers):
            ch_next = min(ch * 2, 512)  # double channels each layer, but cap at 512 to limit params
            layers += [norm(nn.Conv2d(ch, ch_next, kernel_size=4, stride=2, padding=1)), nn.LeakyReLU(0.2, True)]
            ch = ch_next
        layers.append(norm(nn.Conv2d(ch, 1, kernel_size=4, stride=1, padding=1)))
        self.net = nn.Sequential(*layers)

    def forward(self, x): return self.net(x)

# %% ../nbs/03_losses.ipynb #f9ad6db1-0f0e-4e79-82e5-1f171c903561
def calc_dec_loss(decoder, enc_out, img_real, 
                  pos_weight=25.0, # weighting positive (white pixels) to negative (black)
                  ): 
    "decoder loss function)"
    img_recon = decoder(enc_out)
    pos_weight = torch.tensor([pos_weight], device=img_real.device) # white pixels more important than black
    loss_bce = F.binary_cross_entropy_with_logits(img_recon, img_real, pos_weight=pos_weight)
    loss_dec = loss_bce                                       # +... we used to add other losses in the total
    img_recon = torch.sigmoid(img_recon)                      # this is only for viz later; needs sigmoid to -> (0,1) (we may even binarize it)
    return {'dec':loss_dec, 'bce':loss_bce, 'recon':img_recon.detach()}
