"""Pre-encode images using frozen encoder for faster decoder training"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_preencode.ipynb.

# %% auto #0
__all__ = ['preencode']

# %% ../nbs/08_preencode.ipynb #2b6f3731
import os
import torch
from torch.utils.data import DataLoader
from omegaconf import DictConfig, OmegaConf
import hydra
from tqdm.auto import tqdm
from pathlib import Path

from .data import ShiftedTripletDataset
from .swin import SwinEncoder
from .vit import ViTEncoder
from .utils import load_checkpoint

# %% ../nbs/08_preencode.ipynb #8e40339b
@hydra.main(version_base=None, config_path="../configs", config_name="config_swin")
def preencode(cfg: DictConfig):
    device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
    print(f"device = {device}")

    # Load encoder
    ckpt_path = cfg.get('encoder_ckpt', 'checkpoints/SwinEncoder__best.pt')
    if cfg.model.get('encoder', 'vit') == 'swin':
        encoder = SwinEncoder(
            img_height=cfg.data.image_size, img_width=cfg.data.image_size,
            patch_h=cfg.model.patch_h, patch_w=cfg.model.patch_w,
            embed_dim=cfg.model.embed_dim, depths=cfg.model.depths,
            num_heads=cfg.model.num_heads, window_size=cfg.model.window_size,
            mlp_ratio=cfg.model.mlp_ratio, drop_path_rate=cfg.model.drop_path_rate,
        ).to(device)
    else:
        encoder = ViTEncoder(cfg.data.in_channels, cfg.data.image_size,
                             cfg.model.patch_size, cfg.model.dim,
                             cfg.model.depth, cfg.model.heads).to(device)
    encoder = load_checkpoint(encoder, ckpt_path)
    encoder.eval()

    output_dir = Path(os.path.expandvars(os.path.expanduser(str(cfg.preencode.output_dir))))
    output_dir.mkdir(parents=True, exist_ok=True)
    num_passes   = cfg.preencode.get('num_passes', 10)
    batch_size   = cfg.preencode.get('batch_size', 1024)   # large batch; inference only
    batches_per_chunk = cfg.preencode.get('batches_per_chunk', 10)
    print(f"output_dir={output_dir}, num_passes={num_passes}, batch_size={batch_size}, batches_per_chunk={batches_per_chunk}")

    amp_dtype = torch.bfloat16 if device == 'cuda' else torch.float32
    for split in ['train', 'val']:
        print(f"\n=== {split} split ===")
        ds = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split=split,
                                   max_shift_x=cfg.training.max_shift_x,
                                   max_shift_y=cfg.training.max_shift_y)
        chunk_idx = 0
        for pass_num in range(1, num_passes + 1):
            dl = DataLoader(ds, batch_size=batch_size, shuffle=True, num_workers=4, drop_last=False)
            buf = []   # accumulate batches_per_chunk batches before saving
            for batch_num, batch in enumerate(tqdm(dl, desc=f"{split} pass {pass_num}/{num_passes}")):
                with torch.no_grad():
                    with torch.autocast(device_type=device, dtype=amp_dtype):
                        enc1 = encoder(batch['img1'].to(device))
                        enc2 = encoder(batch['img2'].to(device))
                        enc3 = encoder(batch['img3'].to(device))
                rec = {
                    'emb1': [lvl.emb.half().cpu() for lvl in enc1.patches.levels],
                    'emb2': [lvl.emb.half().cpu() for lvl in enc2.patches.levels],
                    'emb3': [lvl.emb.half().cpu() for lvl in enc3.patches.levels],
                    'img1': batch['img1'].bool(), 'img2': batch['img2'].bool(), 'img3': batch['img3'].bool(),
                    'deltas': batch['deltas'], 'scheme': batch['scheme'],
                    'target': batch['target'], 'file_idx': batch['file_idx'],
                }
                buf.append(rec)
                if len(buf) >= batches_per_chunk:
                    save_path = output_dir / f"{split}_chunk{chunk_idx:05d}.pt"
                    torch.save(buf, save_path)
                    print(f"  saved {save_path} ({len(buf)} batches)")
                    buf = []
                    chunk_idx += 1
            if buf:   # save any remaining partial chunk
                save_path = output_dir / f"{split}_chunk{chunk_idx:05d}.pt"
                torch.save(buf, save_path)
                print(f"  saved {save_path} ({len(buf)} batches, partial)")
                buf = []
                chunk_idx += 1
    print("\nPre-encoding complete.")

# %% ../nbs/08_preencode.ipynb #c159f875
#| eval: false
if __name__ == "__main__" and "ipykernel" not in __import__("sys").modules:
    preencode()
