"""Encoder training script for midi_rae"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_train_enc.ipynb.

# %% auto #0
__all__ = ['CurriculumSchedule', 'compute_batch_loss', 'train', 'train_enc_main']

# %% ../nbs/06_train_enc.ipynb #dc166645-c67a-4e9a-9f4b-e78fb90fc7c6
import sys
sys.dont_write_bytecode = True  # I'm getting burned sometimes when it reuses stale PYC files.
import os
os.environ["TORCHINDUCTOR_FX_GRAPH_CACHE"] = "1"
os.environ["PYTHONWARNINGS"] = "ignore::UserWarning:torch._inductor"
os.environ["TORCHINDUCTOR_CACHE_DIR"] = os.path.expanduser("~/.cache/torch/inductor")
os.makedirs(os.environ["TORCHINDUCTOR_CACHE_DIR"], exist_ok=True)
os.environ["WANDB_QUIET"] = "true"

# %% ../nbs/06_train_enc.ipynb #16dcb924-f011-49a7-9602-654bbca5912d
from itertools import chain
import multiprocessing as mp
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import OneCycleLR
import wandb
from hydra import compose, initialize
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf
import hydra
import time 
import gc 
from tqdm.auto import tqdm

from .core import *
from .utils import *
from .vit import ViTEncoder, LightweightMAEDecoder
from .swin import *
from .data import PRPairDataset, ShiftedTripletDataset
from .losses import safe_mean, calc_enc_loss, calc_mae_loss, calc_enc_loss_multiscale
from .viz import make_emb_viz, viz_mae_recon

# %% ../nbs/06_train_enc.ipynb #98edfbef
#  Tuning for PyTorch and others

# cuda card matching
torch.backends.cudnn.benchmark = True
torch.set_float32_matmul_precision('high')

# torch compilation
torch._inductor.config.fx_graph_cache = True
torch._inductor.config.compile_threads = 8
torch._dynamo.config.cache_size_limit = 16
import warnings
warnings.filterwarnings("ignore", message="Online softmax is disabled")
warnings.filterwarnings("ignore", message="failed while executing pow_by_natural")
import logging
logging.getLogger("torch").setLevel(logging.ERROR)

# %% ../nbs/06_train_enc.ipynb #e6d4f354
from bisect import bisect_right

class CurriculumSchedule(): 
    "Manage curriculum learning for shifts in pitch and time."
    def __init__(self, cfg, intervals=None, verbose=True): 
        self.cfg = cfg
        self.max_shifts_x = list(range(cfg.training.init_shift_x, cfg.training.max_shift_x+1))
        self.max_shifts_y = list(range(cfg.training.init_shift_y, cfg.training.max_shift_y+1))
        #if intervals is None: self.intervals = [100, 25, 40, 40, 40, 25, 40, 40, 40, 20, 20, 20]
        if intervals is None: self.intervals = [20, 10, 10, 20, 20, 20, 20, 10, 10, 10, 10, 10]
        elif not isinstance(intervals, (tuple, list)): self.intervals = [intervals]*12 # :shrug: 
        else: self.intervals = intervals
        self.epoch_bounds = []        
        _t = 1 # my epochs start at 1 not zero. shouldn't matter but so it is. 
        for n in self.intervals:
            _t += n; self.epoch_bounds.append(_t)
        if verbose:
            cjprint("CurriculumSchedule:", color="magenta")
            cjprint(f"max_shifts_x: {'  '.join(f'{v:3d}' for v in self.max_shifts_x)}", color="magenta")
            cjprint(f"epoch bounds: {'  '.join(f'{v:3d}' for v in self.epoch_bounds)}", color="magenta")
        self.prev_stage = -1  # for lr schedling 

    def __call__(self, shared_ct_dict, epoch, verbose=False):

        training = shared_ct_dict['training']
        idx = min(bisect_right(self.epoch_bounds, epoch), len(self.max_shifts_x)-1) # which interval we're in; clamp at last
        training['max_shift_x'], training['max_shift_y']  = self.max_shifts_x[idx], self.max_shifts_y[idx]
        if verbose: print(f"curr_learn: max_shift_x = {training['max_shift_x']}, max_shift_y = {training['max_shift_y']}")
        return training

    def step(self, epoch, optimizer):
        stage_idx = min(bisect_right(self.epoch_bounds, epoch), len(self.intervals)-1)
        if stage_idx != self.prev_stage:
            self.scheduler = OneCycleLR(optimizer, max_lr=self.cfg.training.lr,
                                   steps_per_epoch=1, epochs=self.intervals[stage_idx], div_factor=5)
            self.prev_stage = stage_idx
        else:
            self.scheduler.step()

# %% ../nbs/06_train_enc.ipynb #d3f6162a
#@torch.compiler.disable
def compute_batch_loss(batch, encoder, cfg, global_step, mae_decoder=None, ema_encoder=None, mep_model=None, debug=False):
    "Compute loss and return other exal auxiliary variables (for train or val)"
    device = next(encoder.parameters()).device
    
    img1, img2, deltas = [batch[x].to(device, non_blocking=True) for x in ['img1','img2','deltas']]
    img3, target = None, None
    if 'img3' in batch and cfg.training.get('lambda_fact',0) > 0:
        img3, target  = [batch[x].to(device, non_blocking=True) for x in ['img3','target']]

    enc1_fn  = ema_encoder if ema_encoder is not None else encoder   # with ema on, output 1 gets no gradients
    enc_out1 = enc1_fn(img1, mask_ratio=(cfg.training.mask_ratio if mae_decoder is not None else 0))  
    enc_out2 = encoder(img2, mae_mask=enc_out1.mae_mask)            # output 2 always  gets gradients.
    enc_out3 = None
    if 'img3' in batch and cfg.training.get('lambda_fact',0) > 0:
        enc_out3 = encoder(img3, mae_mask=enc_out1.mae_mask)        

    loss_dict = {}
    recon_patches = None
    if mae_decoder is not None: # recon at finest scale
        eo = enc_out2.patches[-1] # readibility/convenience variable
        recon_patches = mae_decoder(enc_out2) 
        if debug:
            for i, lv in enumerate(enc_out2.patches.levels):
                print(f"level {i}: {lv.emb.isnan().any()}, min={lv.emb.min():.4f}, max={lv.emb.max():.4f}")
        loss_dict['mae'] = calc_mae_loss(recon_patches, img2, enc_out2, lambda_visible=cfg.training.get('lambda_visible',0.1)) # created here. 

    if isinstance(enc_out1.patches, HierarchicalPatchState):
        z1 = [lvl.emb for lvl in enc_out1.patches.levels]
        z2 = [lvl.emb for lvl in enc_out2.patches.levels]
        if enc_out3 is not None:
            z3 = [lvl.emb for lvl in enc_out3.patches.levels]  
            non_emptys = [(l1.non_empty, l2.non_empty, l3.non_empty) for l1, l2, l3 in zip(enc_out1.patches.levels, enc_out2.patches.levels, enc_out3.patches.levels)]
        else:
            z3 = None
            l3_iter = enc_out3.patches.levels if enc_out3 is not None else [None] * len(enc_out1.patches.levels)
            non_emptys = [(l1.non_empty, l2.non_empty, l3) for l1, l2, l3  in zip(enc_out1.patches.levels, enc_out2.patches.levels, l3_iter)]
    else:
        z1 = enc_out1.patches.all_emb.reshape(-1, enc_out1.patches[1].dim)
        z2 = enc_out2.patches.all_emb.reshape(-1, enc_out2.patches[1].dim)
        z3 = enc_out3.patches.all_emb.reshape(-1, enc_out3.patches[1].dim) if enc_out3 is not None else None
        non_emtptys =  (enc_out1.patches.all_non_empty, enc_out2.patches.all_non_empty, enc_out3.patches.all_non_empty)

    loss_dict = loss_dict | calc_enc_loss_multiscale(z1, z2, global_step, cfg.data.image_size,  z3=z3, deltas=deltas, target=target,
                non_emptys=non_emptys, lambd=cfg.training.lambd, 
                lambda_anchor=cfg.training.get('lambda_anchor',0.05),  lambda_fact=cfg.training.get('lambda_fact',0.5) )

    
    if mep_model is not None and ema_encoder is not None:           # late addition: Masked Embedding Predictor, across all levels. 
        assert mae_decoder is None, "You can either do MAE or MEP, not both -- Need to save VRAM"  # If you want to run both, run image two through the encoder again, but with no MAE mask. It'll just add to VRAM. 
        mep_target = ema_encoder(img2)
        emb_pred, masks = mep_model(enc_out2)  # predict from masked-input enc_out2, what the comparable embeddings are in enc_out1        
        total_mep_loss = 0
        for lev, (emb, mask) in enumerate(zip(emb_pred, masks)): 
            mep_target_lvl = mep_target.patches[lev].emb.detach()    
            mep_loss = safe_mean((emb[~mask] - mep_target_lvl[~mask])**2)  # mask=0 means masked ,  mean across each level
            loss_dict['levels'][lev]['mep'] = mep_loss.item()          # keep per-level info for logging 
            total_mep_loss = total_mep_loss + mep_loss
        total_mep_loss = total_mep_loss / enc_out2.patches.num_levels  # average over levels
        loss_dict['mep'] = total_mep_loss 

        
    if 'mae' in loss_dict.keys(): loss_dict['loss'] = loss_dict['loss'] +  cfg.training.get('lambda_mae', 1.0) * loss_dict['mae']
    if 'mep' in loss_dict.keys(): loss_dict['loss'] = loss_dict['loss'] +  cfg.training.get('lambda_mep', 1.0) * loss_dict['mep']

    if debug and torch.isnan(loss_dict['loss']):
        cjprint("*** NaN detected! ***", {k: v.item() if hasattr(v, 'item') else v for k, v in loss_dict.items()}, color="red")
        breakpoint()
    return loss_dict, (z1, z2, z3), (enc_out1, enc_out2, enc_out3), recon_patches

# %% ../nbs/06_train_enc.ipynb #69be248f-4310-4da7-81f2-826063804f8d
def train(cfg: DictConfig):
    dict_test = dict(cfg) # force resolution of required fields (e.g. tag=???)
    
    device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
    cjprint(f"config file: {HydraConfig.get().job.config_name}\nconfig: {cfg}\ndevice = {device}",color="green")
    set_seed()

    manager = mp.Manager()
    shared_ct_dict = manager.dict(OmegaConf.to_container(cfg))

    if cfg.training.get('lambda_fact',0) > 0:  # only load pairs unless you need triplets (save memory/computation)
        train_ds = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split='train', max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y, shared=shared_ct_dict) 
        val_ds   = ShiftedTripletDataset(image_dataset_dir=cfg.data.path, split='val',  max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y, shared=shared_ct_dict) 
    else:
        train_ds = PRPairDataset(image_dataset_dir=cfg.data.path, split='train', max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y, shared=shared_ct_dict) 
        val_ds   = PRPairDataset(image_dataset_dir=cfg.data.path, split='val',  max_shift_x=cfg.training.max_shift_x, max_shift_y=cfg.training.max_shift_y, shared=shared_ct_dict) 

    train_dl = DataLoader(train_ds, batch_size=cfg.training.batch_size, num_workers=8, drop_last=True, pin_memory=True, persistent_workers=True, prefetch_factor=4)
    val_dl   = DataLoader(val_ds,   batch_size=cfg.training.batch_size, num_workers=4, drop_last=True, pin_memory=True, persistent_workers=True, prefetch_factor=4)

    # setup models
    cfm = cfg.model 
    patch_size = cfm.get('patch_size', cfm.get('patch_h', 16))
    dim = cfm.get('dim', cfm.get('embed_dim', 256))   
    
    mae_decoder, ema_encoder, mep_model = None, None, None
    if cfm.get('encoder', 'vit') == 'swin':
        dims = tuple(cfm.embed_dim * 2**i for i in range(len(cfm.depths)-1, -1, -1))
        encoder = SwinEncoder(img_height=cfg.data.image_size, img_width=cfg.data.image_size, patch_h=cfm.patch_h, patch_w=cfm.patch_w,
                            embed_dim=cfm.embed_dim, depths=cfm.depths, num_heads=cfm.num_heads, window_size=cfm.window_size,
                            mlp_ratio=cfm.mlp_ratio, drop_path_rate=cfm.drop_path_rate).to(device)
        if cfg.training.get('lambda_mae',0) > 0: mae_decoder = SwinMAEDecoder(patch_size=patch_size, dims=dims).to(device)
        if cfg.training.get('lambda_mep',0) > 0: mep_model   = SwinMaskedEmbeddingPredictor(dims=dims).to(device)
    else:
        encoder = ViTEncoder(cfg.data.in_channels, (cfg.data.image_size, cfg.data.image_size), cfm.patch_size, 
                           cfm.dim, cfm.depth, cfm.heads).to(device)
        if cfg.training.get('lambda_mae',0) >0: mae_decoder = LightweightMAEDecoder(patch_size=patch_size, dim=dim).to(device)
        
    ema_encoder = EMAModel(encoder, eta=cfg.training.ema_eta, update_every=cfg.training.ema_update_every) if cfg.training.ema_eta > 0 else None
    cjprint("encoder, mae_decoder, ema_encoder, mep_model =", encoder.__class__.__name__, mae_decoder.__class__.__name__, ema_encoder.__class__.__name__, mep_model.__class__.__name__, color="cyan")
    cjprint(f"Encoder Total, Trainable: {param_count(encoder)}",color="cyan")
    
    params = list(encoder.parameters()) if mae_decoder is None else list(chain(encoder.parameters(), mae_decoder.parameters()))
    if mep_model is not None: params = list(chain(params, mep_model.parameters()))
    optimizer = torch.optim.AdamW(params, lr=cfg.training.lr)
    epoch_start = 1
    if (cfg.get('checkpoint', False)): # use "+checkpoint=<path>" from CLI
        ckpt_path =  cfg.get('checkpoint',None)
        encoder, ckpt = load_checkpoint(encoder, ckpt_path, return_all=True)
        #optimizer.load_state_dict(ckpt['optimizer_state_dict'])
        try: mae_decoder, ckpt = load_checkpoint(mae_decoder, ckpt_path.replace('Encoder','MAEDecoder'), return_all=True)
        except: pass
        load_optimizer_state_partial(optimizer, ckpt['optimizer_state_dict'], device)
        epoch_start = ckpt['epoch'] + 1 # next epoch after the one completed in thecheckpoint
    print("epoch_start =",epoch_start)
    
    if cfm.get('encoder', 'vit') == 'vit': 
        encoder = torch.compile(encoder, dynamic=True)
    elif False: #  swin compilation takes a while and is fraught with difficulty :-( 
        for i, stage in enumerate(encoder.stages):
            encoder.stages[i] = torch.compile(stage, mode="default")
    if cfg.training.get('init_shift_x',-1) > 0:
        curr_learn = CurriculumSchedule(cfg)
        scheduler = False  # let curr_learn handle schedulers
    else:
        curr_learn = None
        #scheduler = OneCycleLR(optimizer, max_lr=cfg.training.lr, steps_per_epoch=1, epochs=cfg.training.epochs, div_factor=5, 
        #                       **({'last_epoch': epoch_start-1} if epoch_start > 1 else {}))
    scheduler = OneCycleLR(optimizer, max_lr=cfg.training.lr, steps_per_epoch=1, epochs=cfg.training.epochs, div_factor=5)
    for _ in range(epoch_start - 1):
        scheduler.step()

    #scaler = torch.amp.GradScaler(device)

    
    if not(cfg.get('no_wandb', False)): 
        wandb.init(project=cfg.wandb.project, config=dict(cfg))
        wandb.define_metric("epoch")
        wandb.define_metric("*", step_metric="epoch")
        wandb.run.name = f"{cfg.tag}_{wandb.run.name}" # add descriptive tag

    # Training loop
    global_step = (epoch_start - 1) * len(train_dl)
    viz_every = 5
    rprint("And this is training \n","yellow")
    best_val_loss = float('inf')
    for epoch in range(epoch_start, cfg.training.epochs+1):
        if wandb.run is not None: wandb.log({"epoch": epoch})
        encoder.train()
        train_loss = 0
        if curr_learn is not None: 
            curr_learn.step(epoch, optimizer)
            shared_ct_dict['training'] = curr_learn(shared_ct_dict, epoch)
        if epoch==44: # TODO: this is hacky 
            if ema_encoder is not None: ema_encoder.eta = 0.96
        for batch in tqdm(train_dl, desc=f"Epoch {epoch}/{cfg.training.epochs}"):
            global_step += 1
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type='cuda', dtype=torch.bfloat16):
                loss_dict, zs, enc_outs, recon_patches = compute_batch_loss(batch, encoder, cfg, global_step, mae_decoder=mae_decoder, ema_encoder=ema_encoder, mep_model=mep_model)
            #scaler.scale(loss_dict['loss']).backward()
            #scaler.step(optimizer)
            #scaler.update()
            loss_dict['loss'].backward()
            torch.nn.utils.clip_grad_norm_(params, max_norm=1.0)
            optimizer.step()
            if ema_encoder is not None: ema_encoder.update(encoder)
            train_loss += loss_dict['loss'].detach()
            
        # At end of Epoch: validation, viz, etc
        encoder.eval()
        val_loss = 0
        with torch.no_grad():
            for batch in val_dl:
                with torch.autocast(device_type='cuda', dtype=torch.bfloat16):
                    val_loss_dict, zs, enc_outs, recon_patches = compute_batch_loss(batch, encoder, cfg, global_step, mae_decoder=mae_decoder, ema_encoder=ema_encoder, mep_model=mep_model)
                val_loss += val_loss_dict['loss'].item()

            train_loss /= len(train_dl)
            val_loss /= len(val_dl)
            if val_loss < best_val_loss: best_val_loss = val_loss
            print(f"Epoch {epoch}/{cfg.training.epochs}: train_loss={train_loss:.3f} val_loss={val_loss:.3f} (best={best_val_loss:.3f})")
            
            if wandb.run is not None: 
                log = {"lr": optimizer.param_groups[0]['lr'], 'epoch': epoch, 'ema_eta': ema_encoder.eta if ema_encoder is not None else cfg.training.get('ema_eta',0), 
                       "max_shift_x": shared_ct_dict['training']['max_shift_x'], "max_shift_y": shared_ct_dict['training']['max_shift_y']}
                for prefix, ld in [("train", loss_dict), ("val", val_loss_dict)]:
                    for k in ('loss', 'sim', 'sigreg', 'anchor', 'fact', 'mae', 'mep'):
                        log[f"{prefix}_{k}"] = to_scalar(ld.get(k, 0))
                    for l, lvl in enumerate(ld.get('levels', [])):
                        for k, v in lvl.items():
                            log[f"levels/{prefix}_{k}_L{l}"] = to_scalar(v)
                wandb.log(log)
                
                if epoch % viz_every == 0:  
                    rprint("But here's some numbers  ","yellow")
                    cjprint("Sending visualization data",color="green")
                    figs = make_emb_viz(enc_outs, epoch=epoch, encoder=encoder, batch=batch)
                    del figs
                    gc.collect()
                    
                if (mae_decoder is not None) and (epoch % (max(1,viz_every//5)) == 0):
                    eval_tup =viz_mae_recon(recon_patches, batch['img2'], enc_out=enc_outs[-1], epoch=epoch, patch_size=patch_size, return_maps=True)
                    del eval_tup
                    gc.collect()
        save_checkpoint((mae_decoder, encoder), epoch, val_loss, cfg, optimizer=optimizer, tag=cfg.tag) # optimzer gets saved with mae_decoder, not encoder
        freemem()
        if scheduler is not None: scheduler.step()
    return best_val_loss

# %% ../nbs/06_train_enc.ipynb #dc55b9c3
#| eval: false
@hydra.main(version_base=None, config_path="../configs", config_name="config")
def train_enc_main(cfg: DictConfig):
    cjprint(logo, color="red")
    rprint("I just met you \n","yellow")
    cjprint("Encoder training script",color="cyan") 
    best_metric = train(cfg)
    print(f"FINISHED. Best metric: {best_metric:.3f}")
    
if __name__ == "__main__" and "ipykernel" not in __import__("sys").modules:
    train_enc_main()
