"""Training script for the ViT decoder with reconstruction losses"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_train_dec.ipynb.

# %% auto #0
__all__ = ['PreEncodedDataset', 'get_embeddings_batch', 'train']

# %% ../nbs/09_train_dec.ipynb #2f59b81f
import os
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import wandb
from omegaconf import DictConfig
import hydra
from tqdm.auto import tqdm
import lpips

from .vit import ViTEncoder, ViTDecoder
from .losses import PatchGANDiscriminator
from .data import PRPairDataset  # TODO: may need a simpler single-image dataset
from .utils import save_checkpoint

# %% ../nbs/09_train_dec.ipynb #f87c9456
class PreEncodedDataset(Dataset):
    """Load pre-encoded embeddings + images from .pt files"""
    def __init__(self, encoded_dir):
        self.files = sorted([f for f in os.listdir(encoded_dir) if f.endswith('.pt')])
        self.encoded_dir = encoded_dir
        # Load all chunks into memory (adjust if too large)
        self.embeddings, self.images = [], []
        for f in self.files:
            data = torch.load(os.path.join(encoded_dir, f))
            self.embeddings.append(data['embeddings'])
            self.images.append(data['images'])
        self.embeddings = torch.cat(self.embeddings, dim=0)
        self.images = torch.cat(self.images, dim=0)
    
    def __len__(self): return len(self.embeddings)
    def __getitem__(self, idx): return self.embeddings[idx], self.images[idx]

# %% ../nbs/09_train_dec.ipynb #102f0438
def get_embeddings_batch(batch, encoder=None, preencoded=False, device='cuda'):
    """Get embeddings + images from batch, either pre-encoded or computed on-the-fly"""
    if preencoded:
        z, img = batch
        return z.to(device), img.to(device)
    else:
        img = batch['img'].to(device)  # adjust key based on your dataset
        with torch.no_grad():
            z = encoder(img, return_cls_only=False)
        return z, img

# %% ../nbs/09_train_dec.ipynb #198855af
@hydra.main(version_base=None, config_path='../configs', config_name='config')
def train(cfg: DictConfig):
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    preencoded = cfg.get('preencoded', False)
    
    # --- Data ---
    if preencoded:
        train_ds = PreEncodedDataset(cfg.preencode.output_dir + '/train')
        val_ds = PreEncodedDataset(cfg.preencode.output_dir + '/val')
    else:
        # TODO: use a single-image dataset (not pairs)
        train_ds = PRPairDataset(cfg.data.path, split='train', image_size=cfg.data.image_size)
        val_ds = PRPairDataset(cfg.data.path, split='val', image_size=cfg.data.image_size)
    
    train_dl = DataLoader(train_ds, batch_size=cfg.training.batch_size, shuffle=True, num_workers=4)
    val_dl = DataLoader(val_ds, batch_size=cfg.training.batch_size, shuffle=False, num_workers=4)
    
    # --- Models ---
    encoder = None
    if not preencoded:
        encoder = ViTEncoder(cfg.data.in_channels, cfg.data.image_size, cfg.model.patch_size,
                             cfg.model.dim, cfg.model.depth, cfg.model.heads).to(device)
        ckpt = torch.load(cfg.encoder_ckpt)
        encoder.load_state_dict(ckpt['model_state_dict'])
        encoder.eval()  # frozen
        for p in encoder.parameters(): p.requires_grad = False
    
    decoder = ViTDecoder(cfg.data.in_channels, (cfg.data.image_size, cfg.data.image_size),
                         cfg.model.patch_size, cfg.model.dim, 
                         cfg.model.get('dec_depth', 4), cfg.model.get('dec_heads', 8)).to(device)
    
    discriminator = PatchGANDiscriminator(in_ch=cfg.data.in_channels).to(device)
    
    # --- Losses ---
    l1_loss = nn.L1Loss()
    lpips_loss = lpips.LPIPS(net='vgg').to(device)
    
    # --- Optimizers ---
    opt_dec = torch.optim.AdamW(decoder.parameters(), lr=cfg.training.lr)
    opt_disc = torch.optim.AdamW(discriminator.parameters(), lr=cfg.training.lr)
    
    # --- Wandb ---
    wandb.init(project=cfg.wandb.project, config=dict(cfg))
    
    # --- Training loop ---
    for epoch in range(1, cfg.training.epochs + 1):
        decoder.train()
        discriminator.train()
        train_loss = 0
        
        for batch in tqdm(train_dl, desc=f'Epoch {epoch}/{cfg.training.epochs}'):
            z, img_real = get_embeddings_batch(batch, encoder, preencoded, device)
            
            # --- Decode ---
            img_recon = decoder(z)
            
            # --- Discriminator step ---
            opt_disc.zero_grad()
            d_real = discriminator(img_real)
            d_fake = discriminator(img_recon.detach())
            loss_disc = (torch.relu(1 - d_real).mean() + torch.relu(1 + d_fake).mean()) / 2  # hinge loss
            loss_disc.backward()
            opt_disc.step()
            
            # --- Decoder step ---
            opt_dec.zero_grad()
            loss_l1 = l1_loss(img_recon, img_real)
            loss_lpips = lpips_loss(img_recon.repeat(1,3,1,1), img_real.repeat(1,3,1,1)).mean()  # LPIPS wants 3ch
            loss_gan = -discriminator(img_recon).mean()  # generator wants discriminator to say "real"
            
            # TODO: adaptive weighting as in RAE paper
            loss_dec = loss_l1 + 0.1 * loss_lpips + 0.01 * loss_gan
            loss_dec.backward()
            opt_dec.step()
            
            train_loss += loss_dec.item()
        
        train_loss /= len(train_dl)
        print(f'Epoch {epoch}: train_loss={train_loss:.4f}')
        wandb.log({'train_loss': train_loss, 'loss_l1': loss_l1.item(), 
                   'loss_lpips': loss_lpips.item(), 'loss_gan': loss_gan.item(),
                   'loss_disc': loss_disc.item(), 'epoch': epoch})
        
        # TODO: validation, checkpointing, visualization
    
    wandb.finish()

# %% ../nbs/09_train_dec.ipynb #cf0d6973
#| eval: false
if __name__ == "__main__" and "ipykernel" not in __import__("sys").modules:
    train()
