"""utilities"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_utils.ipynb.

# %% auto #0
__all__ = ['to_scalar', 'do_every', 'schmitt_binarize', 'binarize', 'freemem', 'cjprint', 'rprint', 'cchange', 'crevert',
           'set_seed', 'param_count', 'save_checkpoint', 'load_checkpoint', 'load_optimizer_state_partial', 'EMAModel']

# %% ../nbs/04_utils.ipynb #b96051a7
import os 
import torch
import torch
import torch.nn as nn
from copy import deepcopy
import gc
import time
import inspect
import re

# %% ../nbs/04_utils.ipynb #508796f9-1162-4ef7-a630-e5a502041bce
def to_scalar(x): 
    "When you're sick of guessing what you're allowed to do to make it log to WandB..."
    return x.item() if hasattr(x, 'item') else x

# %% ../nbs/04_utils.ipynb #bc32d8fe
_timers = {}

def _parse_interval(s):
    """Parse a human-readable interval string or number into seconds."""
    if isinstance(s, (int, float)):
        return float(s)
    s = str(s).strip().lower()
    units = {'s': 1, 'sec': 1, 'second': 1, 'seconds': 1,
             'm': 60, 'min': 60, 'minute': 60, 'minutes': 60,
             'h': 3600, 'hr': 3600, 'hour': 3600, 'hours': 3600}
    m = re.fullmatch(r'(\d+(?:\.\d+)?)\s*([a-z]+)', s)
    if m:
        val, unit = float(m.group(1)), m.group(2)
        if unit in units:
            return val * units[unit]
    raise ValueError(f"Can't parse interval: {s!r}")

def do_every(interval, id=None, first_true=True):
    """Return True if at least `interval` time has passed since the last True at this call site.
    Sample usage:  do_every('15min'), do_every('1h', 'viz') etc.  
    If `id` is None, the call site is identified by filename and line number; otherwise, it's identified by filename and `id`.  
    This allows you to have multiple independent timers in the same file.
    By default it will be true the first time it's called. Set first_true=False to change that. 
    """
    frame = inspect.stack()[1]
    key = f"{frame.filename}:{id}" if id is not None else f"{frame.filename}:{frame.lineno}"
    seconds = _parse_interval(interval)
    now = time.time()
    is_first = key not in _timers
    if now - _timers.get(key, 0) >= seconds:
        _timers[key] = now
        return first_true if is_first else True
    return False

# %% ../nbs/04_utils.ipynb #378dc3c0
def schmitt_binarize(img, low=0.3, high=0.7):
    """Schmitt trigger binarization along time axis (last dim).
    Hysteresis: once a note is ON it stays ON until value drops below `low`;
    once OFF, stays OFF until value exceeds `high`.
    Reduces fragmentation and binarization noise vs. simple thresholding."""
    out = torch.zeros_like(img)
    state = img[..., 0] > high
    out[..., 0] = state.float()
    for t in range(1, img.shape[-1]):
        col = img[..., t]
        state = torch.where(col > high, torch.ones_like(state, dtype=torch.bool),
                torch.where(col < low,  torch.zeros_like(state, dtype=torch.bool), state))
        out[..., t] = state.float()
    return out

# %% ../nbs/04_utils.ipynb #2f505a33-c562-4d5d-8df7-ae62741e4a86
def binarize(img, thresh=0.5, mode="schmitt", low=0.3, high=0.7):
    """Turn float images into binary floats.
    mode='schmitt' (default): Schmitt trigger with hysteresis along time axis.
    Any other mode: simple threshold at `thresh`."""
    if mode == "schmitt":
        return schmitt_binarize(img, low=low, high=high)
    return (img > thresh).float()

# %% ../nbs/04_utils.ipynb #98431695-656e-41c7-be64-7937bccdf2ec
def freemem():
    "free up unused memory"
    if torch.cuda.is_available():
        torch.cuda.synchronize()
        torch.cuda.empty_cache()
    elif torch.backends.mps.is_available():
        torch.mps.synchronize()
        torch.mps.empty_cache()
    gc.collect()

# %% ../nbs/04_utils.ipynb #a0ed4481-d65c-4d8c-abd8-bcefe291ed3f
def cjprint(*args, color=None, justify="left", width=None, bright=True, revert=True, end=None):
    "Prints optionally colored and/or justified text."
    import shutil
    colors = dict(black=30, red=31, green=32, yellow=33, blue=34, magenta=35, cyan=36, white=37)
    if bright: colors = {k:v+60 for k, v in colors.items() }
    text = " ".join(str(a) for a in args)
    width = shutil.get_terminal_size().columns if width is None else width
    if   justify.startswith("r"): text = text.rjust(width)
    elif justify.startswith("c"): text = text.center(width)
    if color:  text = f"\033[{colors[color]}m{text}"
    if revert: text += "\033[0m"
    print(text, end=end, flush=True)

def rprint(text, color=None, width=None):
    "Prints right-justified text. For backwards compatibility"
    cjprint(text, color=color, justify="r", width=width)

def cchange(color):
    "just changes color for whatever comes next" 
    cjprint("", color=color, revert=False, end="") 

def crevert(): 
    "reverts color to default"
    cjprint("",end="") 

# %% ../nbs/04_utils.ipynb #5ac21fcd-9ef8-4f8b-91ca-56ecaad3827e
def set_seed(seed=42, deterministic=False):
    """Set all random seeds for reproducibility"""
    import random, numpy as np
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = deterministic
    torch.backends.cudnn.benchmark = not deterministic

# %% ../nbs/04_utils.ipynb #a3e6f7d6-d97f-4ea4-a427-2351925bdf41
def param_count(model):
    "Returns total and drainable parameters in a model"
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return total, trainable

# %% ../nbs/04_utils.ipynb #71615b73-c28e-41b0-9905-a99045419702
def save_checkpoint(model, epoch, val_loss, cfg, optimizer=None, save_every=25, n_keep=5, verbose=True, tag=""):
    """Saves new checkpoint, keeps best & the most recent n_keep.
       Can loop over multiple models. (Saves separate files for each model)"""
    if not hasattr(save_checkpoint, 'best_val_loss'):
        save_checkpoint.best_val_loss = float('inf')
    if (epoch % save_every != 0 and val_loss >= save_checkpoint.best_val_loss) or (epoch < save_every): return

    os.makedirs('checkpoints', exist_ok=True)
    models = model if isinstance(model, (list, tuple)) else [model]
    added_opt = False 
    for i, m in enumerate(models):
        if m is None: continue
        ckpt = {'epoch': epoch, 'model_state_dict': getattr(m, '_orig_mod', m).state_dict(), 'config': dict(cfg), 'val_loss': val_loss}
        if (optimizer is not None) and (not added_opt):
            added_opt = True
            ckpt = ckpt | {'optimizer_state_dict': optimizer.state_dict()}  # Only first model on list gets optimizer in its ckpt file.

        mtag = f"{getattr(m, '_orig_mod', m).__class__.__name__}_{tag}"
        if epoch % save_every == 0:
            if verbose: 
                print(f"Saving checkpoint to checkpoints/{mtag}ckpt_epoch{epoch}.pt")
                rprint("Recall me maybe \n","yellow")
            torch.save(ckpt, f'checkpoints/{mtag}ckpt_epoch{epoch}.pt')
        if val_loss < save_checkpoint.best_val_loss:
            torch.save(ckpt, f'checkpoints/{mtag}_best.pt')

        # delete any checkpoints older than the n_keep-th one
        ckpts = sorted([f for f in os.listdir('checkpoints') if f.startswith(f'{mtag}ckpt_epoch')],
                   key=lambda x: os.path.getmtime(f'checkpoints/{x}'))
        for old in ckpts[:-n_keep]: os.remove(f'checkpoints/{old}')

    if val_loss <= save_checkpoint.best_val_loss:
        save_checkpoint.best_val_loss = val_loss

# %% ../nbs/04_utils.ipynb #55fb9d50
def load_checkpoint(model, ckpt_path:str, return_all=False, weights_only=False, strict=False):
    "loads a model (and maybe other things) from a checkpoint file"
    device = next(model.parameters()).device
    ckpt_path = os.path.expandvars(os.path.expanduser(ckpt_path))
    ckpt = torch.load(ckpt_path, map_location=device, weights_only=weights_only)
    ckpt['model_state_dict'] = {k.replace('_orig_mod.', ''): v for k, v in ckpt['model_state_dict'].items()}
    model.load_state_dict(ckpt['model_state_dict'], strict=strict)
    print(f">>> Loaded {model.__class__.__name__} checkpoint from {ckpt_path}")
    return (model, ckpt) if return_all else model

# %% ../nbs/04_utils.ipynb #9ce51e34-44e4-45c3-9a7b-86cfe714726d
def load_optimizer_state_partial(optimizer, ckpt_opt, device):
    """Load optimizer state for as many params as the checkpoint has, ignoring extras. 
    Because some sometimes shit breaks"""
    ckpt_state = ckpt_opt['state']
    all_params = [p for group in optimizer.param_groups for p in group['params']]
    for i, param in enumerate(all_params):
        if i in ckpt_state:
            optimizer.state[param] = {
                k: v.to(device) if torch.is_tensor(v) else v
                for k, v in ckpt_state[i].items() }

# %% ../nbs/04_utils.ipynb #44938a52-0c59-4de8-90fe-97f4ab607632
class EMAModel(nn.Module):
    """Exponential moving average wrapper for stable teacher-student training.

    If eta_warmup_steps > 0, uses the EDM-style ramping schedule:
        eta_t = min(eta, (1 + step) / (10 + step))
    which starts near 0 and asymptotes to eta, avoiding stale EMA early in training.
    """
    def __init__(self, model, eta=0.99, update_every=1, dtype=torch.bfloat16, eta_warmup_steps=0):
        super().__init__()
        self.eta, self.update_every, self.dtype = eta, update_every, dtype
        self.eta_warmup_steps = eta_warmup_steps
        self.register_buffer('_steps', torch.tensor(0))
        self.ema = deepcopy(model).to(dtype)
        for p in self.ema.parameters(): p.requires_grad_(False)

    def _current_eta(self):
        if self.eta_warmup_steps <= 0: return self.eta
        s = self._steps.item()
        return min(self.eta, (1 + s) / (10 + s))

    def update(self, model):
        self._steps += 1
        if self._steps % self.update_every != 0: return
        eta = self._current_eta()
        with torch.no_grad():
            for p_ema, p in zip(self.ema.parameters(), model.parameters()):
                p_ema.data.mul_(eta).add_(p.data.to(p_ema.data), alpha=1 - eta)
            for b_ema, b in zip(self.ema.buffers(), model.buffers()):
                b_ema.data.copy_(b.data.to(b_ema.data))  # buffers copy directly, no EMA

    def forward(self, x, **kwargs):
        with torch.no_grad():
            return self.ema(x, **kwargs)
